"""Cross-store resolve-through: doc_store figures → outputs_index rows (d2a3537a).

This is the connective glue between two EXISTING stores (not a sixth database):

* ``meridian.outputs_indexer`` — Wave A's persistent DuckDB ``outputs_index``
  table + ``OutputsFtsIndex`` (BM25 search, ``generating_script`` column,
  canonical-vs-archival flag).
* ``meridian.doc_store`` — the semantic ``doc_figures`` table (c623e648), whose
  rows carry a ``file_path``.

A figure whose ``file_path`` names an already-indexed run output should resolve
THROUGH to that output's row — so "does this plot already exist?" +
"where is it referenced in my thesis?" collapse into one lookup.

Exercises:
* ``OutputsFtsIndex.resolve_output`` — exact (path-normalized) equality lookup,
  NOT a BM25 relevance search; returns generating_script + canonical/archival
  flag + fingerprint, or None cleanly for a miss.
* ``_normalize_output_path`` — a figure stored with back-slashes / trailing
  slash / mixed case still resolves on Windows.
* ``resolve_figure_output`` (module-level stateless) — walk + build + resolve.
* ``DocStructureStore.find_similar_figures(..., output_resolver=...)`` and
  ``DocStructureStore.resolve_figure_output(...)`` — the doc_store side attaches
  ``linked_output`` to each figure via the injected resolver seam.
* An archival ``_old`` variant resolves through and is FLAGGED is_archival.
* The ``find_similar_figure`` MCP tool resolves through when given outputs_dir.
"""
from __future__ import annotations

import asyncio
import json
import os

import pytest

from meridian import doc_store
from meridian import db as db_module
from meridian import outputs_indexer as oi


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _write(path, text: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _seed_outputs(outputs_dir):
    """A small outputs tree: a canonical plot json + a byte-identical _old twin."""
    os.makedirs(outputs_dir, exist_ok=True)
    _write(
        os.path.join(outputs_dir, "scatter.json"),
        json.dumps({"generating_script": "plot_scatter.py",
                    "xdata": [1, 2, 3], "ydata": [4, 5, 6]}),
    )
    # byte-identical archival twin → SHA confirms archival
    _write(
        os.path.join(outputs_dir, "scatter_old.json"),
        json.dumps({"generating_script": "plot_scatter.py",
                    "xdata": [1, 2, 3], "ydata": [4, 5, 6]}),
    )
    # clean CSV header → columns are alpha/beta; a separate comment-marker CSV
    # exercises the inferred generating_script path without colliding with the
    # header row.
    _write(
        os.path.join(outputs_dir, "table.csv"),
        "alpha,beta\n1,2\n",
    )
    _write(
        os.path.join(outputs_dir, "marked.csv"),
        "# generated by build_table.py\nx,y\n1,2\n",
    )
    return outputs_dir


async def _open_store(tmp_path) -> doc_store.DocStructureStore:
    conn = await db_module.init_db(str(tmp_path / "doc_structure.db"))
    store = doc_store.DocStructureStore(conn)
    await store.ensure_schema()
    return store


# ---------------------------------------------------------------------------
# _normalize_output_path — cross-platform equality key
# ---------------------------------------------------------------------------

def test_normalize_output_path_unifies_separators_and_blanks():
    a = oi._normalize_output_path("/repo/outputs/plot.json")
    b = oi._normalize_output_path("/repo/outputs/./plot.json")
    assert a == b
    # back-slash variant of the same absolute path normalizes identically
    c = oi._normalize_output_path(os.path.join("sub", "x.csv"))
    d = oi._normalize_output_path("sub/x.csv")
    assert c == d
    # blank / non-string → empty key (never matches)
    assert oi._normalize_output_path("") == ""
    assert oi._normalize_output_path("   ") == ""
    assert oi._normalize_output_path(None) == ""
    assert oi._normalize_output_path(123) == ""


# ---------------------------------------------------------------------------
# OutputsFtsIndex.resolve_output — exact path lookup, not BM25
# ---------------------------------------------------------------------------

def test_resolve_output_returns_row_with_generating_script(tmp_path):
    outputs = _seed_outputs(str(tmp_path / "outputs"))
    idx = oi.OutputsFtsIndex(outputs)
    try:
        idx.rebuild()
        row = idx.resolve_output(os.path.join(outputs, "scatter.json"))
        assert row is not None
        assert os.path.basename(row["path"]) == "scatter.json"
        assert row["generating_script"] == "plot_scatter.py"
        assert row["is_archival"] is False
        assert row["json_keys"] and "generating_script" in row["json_keys"]
    finally:
        idx.close()


def test_resolve_output_miss_returns_none_cleanly(tmp_path):
    outputs = _seed_outputs(str(tmp_path / "outputs"))
    idx = oi.OutputsFtsIndex(outputs)
    try:
        idx.rebuild()
        # a path that is not an indexed output resolves to None (no crash)
        assert idx.resolve_output(os.path.join(outputs, "nope.png")) is None
        assert idx.resolve_output("") is None
        assert idx.resolve_output("   ") is None
    finally:
        idx.close()


def test_resolve_output_flags_archival_variant(tmp_path):
    outputs = _seed_outputs(str(tmp_path / "outputs"))
    idx = oi.OutputsFtsIndex(outputs)
    try:
        idx.rebuild()
        old = idx.resolve_output(os.path.join(outputs, "scatter_old.json"))
        assert old is not None
        assert old["is_archival"] is True
        assert os.path.basename(old["canonical_path"]) == "scatter.json"
    finally:
        idx.close()


def test_resolve_output_matches_despite_separator_differences(tmp_path):
    outputs = _seed_outputs(str(tmp_path / "outputs"))
    idx = oi.OutputsFtsIndex(outputs)
    try:
        idx.rebuild()
        # feed the path with forward slashes even if the OS stored back-slashes
        forward = (os.path.join(outputs, "scatter.json")).replace("\\", "/")
        row = idx.resolve_output(forward)
        assert row is not None
        assert os.path.basename(row["path"]) == "scatter.json"
    finally:
        idx.close()


# ---------------------------------------------------------------------------
# resolve_figure_output — stateless module-level walk+build+resolve
# ---------------------------------------------------------------------------

def test_module_resolve_figure_output_roundtrip(tmp_path):
    outputs = _seed_outputs(str(tmp_path / "outputs"))
    hit = oi.resolve_figure_output(outputs, os.path.join(outputs, "table.csv"))
    assert hit is not None
    assert hit["csv_columns"] == ["alpha", "beta"]
    # a CSV carrying a 'generated by' comment marker resolves through with the
    # inferred generating_script.
    marked = oi.resolve_figure_output(outputs, os.path.join(outputs, "marked.csv"))
    assert marked is not None
    assert marked["generating_script"] == "build_table.py"
    # miss / bad dir / blank → None
    assert oi.resolve_figure_output(outputs, os.path.join(outputs, "ghost.csv")) is None
    assert oi.resolve_figure_output(str(tmp_path / "does-not-exist"),
                                    os.path.join(outputs, "table.csv")) is None
    assert oi.resolve_figure_output(outputs, "") is None


# ---------------------------------------------------------------------------
# doc_store side — find_similar_figures(output_resolver=...) attaches linked_output
# ---------------------------------------------------------------------------

def test_find_similar_figures_resolves_through_to_output(tmp_path):
    async def _run():
        outputs = _seed_outputs(str(tmp_path / "outputs"))
        canonical = os.path.join(outputs, "scatter.json")
        store = await _open_store(tmp_path)
        idx = oi.OutputsFtsIndex(outputs)
        try:
            idx.rebuild()
            doc = await store.put_document("proj-x", "docx", [], source="thesis.docx")
            # one figure whose file_path IS the indexed output, one that is not
            await store.put_figures(doc["id"], [
                {"file_path": canonical, "caption": "Figure 1: scatter of x vs y"},
                {"file_path": os.path.join(outputs, "unindexed.png"),
                 "caption": "Figure 2: a photo"},
            ])
            matches = await store.find_similar_figures(
                doc["id"], "scatter of x vs y", limit=5,
                output_resolver=idx.resolve_output,
            )
            by_cap = {m["caption"]: m for m in matches}
            linked = by_cap["Figure 1: scatter of x vs y"]["linked_output"]
            assert linked is not None
            assert linked["generating_script"] == "plot_scatter.py"
            assert linked["is_archival"] is False
            # a figure that names no indexed output resolves to None cleanly
            assert by_cap["Figure 2: a photo"]["linked_output"] is None
        finally:
            idx.close()

    asyncio.run(_run())


def test_find_similar_figures_without_resolver_has_no_linked_output(tmp_path):
    async def _run():
        store = await _open_store(tmp_path)
        doc = await store.put_document("proj-x", "docx", [], source="t.docx")
        await store.put_figures(doc["id"], [
            {"file_path": "/o/scatter.json", "caption": "Figure 1: scatter"},
        ])
        matches = await store.find_similar_figures(doc["id"], "scatter", limit=5)
        assert matches
        # No resolver → the cross-store hop is skipped entirely, not None-valued.
        assert "linked_output" not in matches[0]

    asyncio.run(_run())


def test_store_resolve_figure_output_single(tmp_path):
    async def _run():
        outputs = _seed_outputs(str(tmp_path / "outputs"))
        canonical = os.path.join(outputs, "scatter.json")
        store = await _open_store(tmp_path)
        idx = oi.OutputsFtsIndex(outputs)
        try:
            idx.rebuild()
            doc = await store.put_document("proj-x", "docx", [], source="t2.docx")
            await store.put_figures(doc["id"], [
                {"file_path": canonical, "caption": "Figure 1: scatter"},
            ])
            hit = await store.resolve_figure_output(
                doc["id"], canonical, idx.resolve_output,
            )
            assert hit is not None
            assert hit["figure"]["caption"] == "Figure 1: scatter"
            assert hit["linked_output"]["generating_script"] == "plot_scatter.py"
            # no figure at that path → None
            miss = await store.resolve_figure_output(
                doc["id"], os.path.join(outputs, "table.csv"), idx.resolve_output,
            )
            assert miss is None
        finally:
            idx.close()

    asyncio.run(_run())


def test_resolver_that_raises_is_swallowed(tmp_path):
    async def _run():
        store = await _open_store(tmp_path)
        doc = await store.put_document("proj-x", "docx", [], source="t3.docx")
        await store.put_figures(doc["id"], [
            {"file_path": "/o/scatter.json", "caption": "Figure 1: scatter"},
        ])

        def _boom(_path):
            raise RuntimeError("resolver exploded")

        matches = await store.find_similar_figures(
            doc["id"], "scatter", limit=5, output_resolver=_boom,
        )
        # A resolver that raises → linked_output None, never crashes the match.
        assert matches[0]["linked_output"] is None

    asyncio.run(_run())


# ---------------------------------------------------------------------------
# MCP tool surface — find_similar_figure resolves through when given outputs_dir
# ---------------------------------------------------------------------------

def test_mcp_find_similar_figure_resolves_through(tmp_path, monkeypatch):
    async def _run():
        from meridian import server as mh

        outputs = _seed_outputs(str(tmp_path / "outputs"))
        canonical = os.path.join(outputs, "scatter.json")

        # Seed the doc store the handler resolves to (env-scoped sidecar).
        sidecar = str(tmp_path / "mcp_doc_structure.db")
        monkeypatch.setenv("MERIDIAN_DOC_STORE_URL", sidecar)
        doc_store._reset_doc_store_cache()

        db = await db_module.init_db(":memory:")
        try:
            proj = await db_module.create_project(db, "xstore-proj")
            pid = proj["id"]
            seed = await doc_store.open_doc_store_for(
                plan=None, hosted=False, data_dir=str(tmp_path),
                tenant_pg_url=None, override_url=sidecar,
            )
            await seed.put_document(pid, "docx", [], source="paper.docx")
            doc_row = await seed.get_document(pid, "paper.docx")
            await seed.put_figures(doc_row["id"], [
                {"file_path": canonical, "caption": "Figure 1: scatter of x vs y"},
            ])

            # Without outputs_dir → pure fuzzy match, no linked_output key.
            plain = await mh._dispatch_mcp_tool(
                "find_similar_figure",
                {"project_id": pid, "doc": "paper.docx",
                 "description_or_path": "scatter of x vs y"},
                db, str(tmp_path),
            )
            assert "error" not in plain
            assert "linked_output" not in plain["matches"][0]

            # With outputs_dir → the figure resolves THROUGH to its output row.
            res = await mh._dispatch_mcp_tool(
                "find_similar_figure",
                {"project_id": pid, "doc": "paper.docx",
                 "description_or_path": "scatter of x vs y",
                 "outputs_dir": outputs},
                db, str(tmp_path),
            )
            assert "error" not in res, res
            linked = res["matches"][0].get("linked_output")
            assert linked is not None
            assert linked["generating_script"] == "plot_scatter.py"
            assert linked["is_archival"] is False
        finally:
            await db.close()
            await doc_store.close_all_doc_stores()

    asyncio.run(_run())
