"""Tests for sprint item 2ae25966 — expose find_outputs_by_source (script/data
source -> outputs it produced) as a CORE MCP tool.

Prior state (confirmed by investigation): find_outputs_by_source already
existed and was already wired as its own ``@mcp.tool()`` in
``extensions/meridian-outputs/meridian_outputs/provenance.py`` /
``server.py`` — but that is the meridian-outputs TUNNEL PLUGIN's own local
MCP server, only reachable by a self-hosted user running ``--tunnel``. It was
never wired into the CORE ``meridian/server.py`` MCP tool catalog that
hosted-tier / no-tunnel clients talk to directly — only the forward
direction (``resolve_figure_output``, folded into ``find_similar_figure``'s
cross-store resolve-through) was reachable there.

This file covers the new core-side wiring end to end, mirroring the existing
``search_outputs`` pattern (5116078b cached incremental index, 0dedff91
hosted-mode guard + 1365e01a tunnel-proxy fallback, mcp_tools.py registration
metadata):

1. ``outputs_indexer.OutputsFtsIndex.find_by_source`` — the reverse SQL scan
   over the recorded ``generating_script`` column (exact + basename tiers).
2. ``outputs_indexer.find_outputs_by_source`` — the stateless, cached-index
   module-level wrapper (mirrors ``resolve_figure_output``/``search_outputs``).
3. MCP tool registration: present + read-only in ``_MCP_TOOLS_LIST`` /
   ``_READ_ONLY_TOOLS``, with the expected required schema fields.
4. End-to-end dispatch via ``server._dispatch_mcp_tool`` on a REAL temp
   outputs tree — proves the new core tool actually returns real
   reverse-lookup results, not just plumbing.
5. Required-arg guards (outputs_dir, source_path).
6. Hosted-mode guard + tunnel-proxy fallback (0dedff91 / 1365e01a), matching
   the same contract already covered for search_outputs/annotate_outputs in
   tests/test_1365e01a_outputs_tunnel_routing.py.
"""
from __future__ import annotations

import asyncio
import json
import os
import time
import unittest.mock as mock

import pytest

from meridian import outputs_indexer as oi


def _write(path, text: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _run(coro):
    return asyncio.run(coro)


# ---------------------------------------------------------------------------
# OutputsFtsIndex.find_by_source — direct class-level coverage
# ---------------------------------------------------------------------------

def test_find_by_source_exact_and_basename_tiers(tmp_path):
    _write(
        tmp_path / "run_a.csv",
        "# generated by analysis/run.py\ntemp,pressure\n300,101\n",
    )
    _write(
        tmp_path / "run_b.json",
        json.dumps({"generated_by": "run.py", "value": 1}),
    )
    _write(
        tmp_path / "unrelated.json",
        json.dumps({"generating_script": "other_script.py", "value": 2}),
    )
    index = oi.OutputsFtsIndex(str(tmp_path))
    index.rebuild(max_seconds=None)

    matches = index.find_by_source("analysis/run.py")
    paths = {os.path.basename(m["path"]) for m in matches}
    # run_a.csv matches via the exact tier (generating_script recorded
    # verbatim as "analysis/run.py"); run_b.json matches via the basename
    # tier (recorded as bare "run.py", same final component).
    assert paths == {"run_a.csv", "run_b.json"}
    assert all(m["generating_script"] for m in matches)


def test_find_by_source_no_match_for_unrelated_source(tmp_path):
    _write(
        tmp_path / "run_a.csv",
        "# generated by generate_baselines.py\nx,y\n1,2\n",
    )
    index = oi.OutputsFtsIndex(str(tmp_path))
    index.rebuild(max_seconds=None)
    assert index.find_by_source("completely_different_script.py") == []


def test_find_by_source_sorts_newest_first_by_mtime(tmp_path):
    older = tmp_path / "older.csv"
    newer = tmp_path / "newer.csv"
    _write(older, "# generated by run.py\nx,y\n1,2\n")
    _write(newer, "# generated by run.py\nx,y\n3,4\n")
    now = time.time()
    os.utime(older, (now - 1000, now - 1000))
    os.utime(newer, (now, now))

    index = oi.OutputsFtsIndex(str(tmp_path))
    index.rebuild(max_seconds=None)
    matches = index.find_by_source("run.py")
    assert [os.path.basename(m["path"]) for m in matches] == [
        "newer.csv", "older.csv",
    ]


def test_find_by_source_blank_source_returns_empty(tmp_path):
    index = oi.OutputsFtsIndex(str(tmp_path))
    index.rebuild(max_seconds=None)
    assert index.find_by_source("") == []
    assert index.find_by_source(None) == []  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Module-level find_outputs_by_source — stateless, cached-index wrapper
# ---------------------------------------------------------------------------

def test_module_find_outputs_by_source_empty_source_path(tmp_path):
    result = oi.find_outputs_by_source(str(tmp_path), "")
    assert result == {
        "outputs_dir": str(tmp_path), "source_path": "", "outputs": [], "total": 0,
    }


def test_module_find_outputs_by_source_missing_dir():
    result = oi.find_outputs_by_source("/nonexistent/dir/xyz", "gen.py")
    assert result["outputs"] == []
    assert result["total"] == 0


def test_module_find_outputs_by_source_roundtrip(tmp_path):
    outputs = str(tmp_path)
    _write(
        tmp_path / "run_a.json",
        json.dumps({
            "generating_script": "width_baseline_generator/generate_baselines.py",
            "width_px": 1.2,
        }),
    )
    _write(
        tmp_path / "run_b.json",
        json.dumps({
            "generating_script": "width_baseline_generator/generate_baselines.py",
            "width_px": 1.3,
        }),
    )
    _write(
        tmp_path / "unrelated.json",
        json.dumps({"generating_script": "other_script.py", "value": 1}),
    )

    result = oi.find_outputs_by_source(
        outputs,
        "C:/Users/dev/project/width_baseline_generator/generate_baselines.py",
    )
    assert result["total"] == 2
    paths = {os.path.basename(o["path"]) for o in result["outputs"]}
    assert paths == {"run_a.json", "run_b.json"}
    assert result["source_path"] == (
        "C:/Users/dev/project/width_baseline_generator/generate_baselines.py"
    )


def test_module_find_outputs_by_source_respects_limit_and_reports_total(tmp_path):
    for i in range(5):
        _write(
            tmp_path / f"run_{i}.csv",
            "# generated by sweep.py\nx,y\n1,2\n",
        )
    result = oi.find_outputs_by_source(str(tmp_path), "sweep.py", limit=2)
    assert result["total"] == 5
    assert len(result["outputs"]) == 2


def test_module_find_outputs_by_source_reuses_cached_index(tmp_path, monkeypatch):
    """Mirrors test_search_outputs_reuses_cached_index_across_calls: repeat
    calls on the same outputs_dir hit the SAME cached, already-populated
    OutputsFtsIndex rather than starting a fresh manifest each time."""
    monkeypatch.setattr(oi, "_index_cache", oi.OrderedDict())
    _write(tmp_path / "run_a.csv", "# generated by run.py\nx,y\n1,2\n")

    r1 = oi.find_outputs_by_source(str(tmp_path), "run.py")
    assert r1["total"] == 1
    key = oi._cache_key(str(tmp_path))
    cached = oi._index_cache[key]

    r2 = oi.find_outputs_by_source(str(tmp_path), "run.py")
    assert oi._index_cache[key] is cached
    assert r2["total"] == 1


# ---------------------------------------------------------------------------
# MCP tool registration (mirrors search_outputs's registration tests)
# ---------------------------------------------------------------------------

def test_find_outputs_by_source_registered_read_only_in_tool_list():
    from meridian.mcp_tools import _MCP_TOOLS_LIST, _READ_ONLY_TOOLS

    by_name = {t["name"]: t for t in _MCP_TOOLS_LIST}
    assert "find_outputs_by_source" in by_name
    schema = by_name["find_outputs_by_source"]["inputSchema"]
    assert set(schema["required"]) == {"outputs_dir", "source_path"}
    assert "find_outputs_by_source" in _READ_ONLY_TOOLS
    assert by_name["find_outputs_by_source"]["annotations"]["readOnlyHint"] is True
    assert by_name["find_outputs_by_source"]["annotations"]["destructiveHint"] is False


def test_find_outputs_by_source_has_example_call():
    from meridian.mcp_tools import _TOOL_EXAMPLES

    assert "find_outputs_by_source" in _TOOL_EXAMPLES
    assert "find_outputs_by_source(" in _TOOL_EXAMPLES["find_outputs_by_source"]


def test_find_outputs_by_source_category_and_workflow_tier():
    from meridian.mcp_tools import _TOOL_CATEGORY, _TOOL_WORKFLOW_TIER

    assert _TOOL_CATEGORY["find_outputs_by_source"] == "code-intel"
    assert _TOOL_WORKFLOW_TIER["find_outputs_by_source"] == "common-support"


# ---------------------------------------------------------------------------
# End-to-end dispatch via _dispatch_mcp_tool (the hosted /mcp route path) —
# proves the new core tool actually returns real reverse-lookup results.
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_find_outputs_by_source_dispatches_end_to_end(tmp_path):
    from meridian import server as srv

    _write(
        tmp_path / "metrics.csv",
        "# generated by analysis/train.py\naccuracy,loss\n0.9,0.1\n",
    )
    _write(
        tmp_path / "unrelated.csv",
        "# generated by other_thing.py\nx,y\n1,2\n",
    )

    result = await srv._dispatch_mcp_tool(
        "find_outputs_by_source",
        {"outputs_dir": str(tmp_path), "source_path": "analysis/train.py"},
        None, "/tmp",
    )
    assert isinstance(result, dict)
    assert result["source_path"] == "analysis/train.py"
    assert result["total"] == 1
    assert len(result["outputs"]) == 1
    assert result["outputs"][0]["path"].endswith("metrics.csv")
    assert result["outputs"][0]["generating_script"] == "analysis/train.py"


@pytest.mark.asyncio
async def test_find_outputs_by_source_dispatch_no_match_returns_empty_not_error(tmp_path):
    from meridian import server as srv

    _write(tmp_path / "run_a.csv", "# generated by run.py\nx,y\n1,2\n")

    result = await srv._dispatch_mcp_tool(
        "find_outputs_by_source",
        {"outputs_dir": str(tmp_path), "source_path": "totally_unrelated.py"},
        None, "/tmp",
    )
    assert result["outputs"] == []
    assert result["total"] == 0
    assert "error" not in result


@pytest.mark.asyncio
async def test_dispatch_find_outputs_by_source_requires_outputs_dir():
    from meridian import server as srv

    with pytest.raises(ValueError, match="outputs_dir is required"):
        await srv._dispatch_mcp_tool(
            "find_outputs_by_source", {"source_path": "run.py"}, None, "/tmp",
        )


@pytest.mark.asyncio
async def test_dispatch_find_outputs_by_source_requires_source_path(tmp_path):
    from meridian import server as srv

    with pytest.raises(ValueError, match="source_path is required"):
        await srv._dispatch_mcp_tool(
            "find_outputs_by_source", {"outputs_dir": str(tmp_path)}, None, "/tmp",
        )


# ---------------------------------------------------------------------------
# Hosted-mode guard + tunnel-proxy fallback (0dedff91 / 1365e01a parity)
# ---------------------------------------------------------------------------

def _run_outputs_call(name: str, arguments: dict, hosted: bool = True,
                       tenant: "dict | None" = None) -> dict:
    import meridian.server  # noqa: F401 — initialise server module before handler import
    from meridian.mcp import handler as mh

    with mock.patch("meridian.mcp.handler._hosted_mode", return_value=hosted):
        return _run(mh._handle_outputs_tools(
            name, arguments,
            db=None, data_dir="/tmp",
            tenant=tenant, _mcp_tenant_id=None,
        ))


def test_find_outputs_by_source_hosted_no_tenant_returns_honest_error():
    result = _run_outputs_call(
        "find_outputs_by_source",
        {"outputs_dir": "/local/outputs", "source_path": "run.py"},
        hosted=True,
        tenant=None,
    )
    assert result.get("hosted") is True
    assert result.get("tunnel_tried") is False
    assert result["outputs"] == []
    assert result["total"] == 0
    assert "cannot run on hosted Meridian" in result["error"]


def test_find_outputs_by_source_hosted_with_tenant_no_tunnel_returns_honest_error(monkeypatch):
    from meridian.routes import tunnel as tunnel_mod

    monkeypatch.setattr(tunnel_mod, "has_active_tunnel", lambda tenant_id: False)
    monkeypatch.setattr(tunnel_mod, "_tunnel_tool_routes", {})

    result = _run_outputs_call(
        "find_outputs_by_source",
        {"outputs_dir": "/local/outputs", "source_path": "run.py"},
        hosted=True,
        tenant={"id": "tenant-abc"},
    )
    assert result.get("hosted") is True
    assert result.get("tunnel_tried") is True
    assert result["outputs"] == []


def test_find_outputs_by_source_hosted_with_tunnel_proxies_successfully(monkeypatch):
    from meridian.routes import tunnel as tunnel_mod

    monkeypatch.setattr(tunnel_mod, "has_active_tunnel", lambda tenant_id: True)
    monkeypatch.setattr(tunnel_mod, "_tunnel_tool_routes", {
        "tenant-abc": {"filesystem__find_outputs_by_source": "fs"}
    })
    proxied = {
        "outputs_dir": "/local/outputs",
        "source_path": "run.py",
        "outputs": [{"path": "/local/outputs/run_1/metrics.csv"}],
        "total": 1,
    }
    monkeypatch.setattr(
        tunnel_mod, "call_tunnel_tool",
        mock.AsyncMock(return_value={
            "content": [{"type": "text", "text": json.dumps(proxied)}]
        }),
    )
    monkeypatch.setattr(tunnel_mod, "list_tunnel_tools", mock.AsyncMock(return_value=[]))

    result = _run_outputs_call(
        "find_outputs_by_source",
        {"outputs_dir": "/local/outputs", "source_path": "run.py"},
        hosted=True,
        tenant={"id": "tenant-abc"},
    )

    assert result == proxied
    assert "error" not in result


def test_find_outputs_by_source_missing_args_raise_even_in_hosted_mode(monkeypatch):
    """Non-regression: required-arg guards fire before the hosted-mode check."""
    monkeypatch.setattr("meridian.mcp.handler._hosted_mode", lambda: True)
    import meridian.server  # noqa: F401
    from meridian.mcp import handler as mh

    with pytest.raises(ValueError, match="outputs_dir is required"):
        _run(mh._handle_outputs_tools(
            "find_outputs_by_source", {"source_path": "run.py"},
            db=None, data_dir="/tmp", tenant={"id": "t"}, _mcp_tenant_id=None,
        ))
    with pytest.raises(ValueError, match="source_path is required"):
        _run(mh._handle_outputs_tools(
            "find_outputs_by_source", {"outputs_dir": "/local/outputs"},
            db=None, data_dir="/tmp", tenant={"id": "t"}, _mcp_tenant_id=None,
        ))
