"""Coverage for the persistent outputs FTS layer + search_outputs (a0e9133e / 5848e8c7).

Exercises the build-on-top of the on-demand glob indexer (06df6ab3 Part 2):

* Persistent DuckDB ``outputs_index`` table + native FTS (Okapi BM25): the table
  is built from a real temp outputs tree (csv/json/npy + other files), and a
  multi-word BM25 query ranks the relevant rows first.
* Per-file cheap fingerprint (5848e8c7): CSV column names, JSON top-level keys,
  and an inferred ``generating_script``.
* Canonical-vs-archival, TWO-STAGE, NEVER destructive: a filename heuristic
  flags candidates; a SHA-256 hash CONFIRMS. Identical content across a
  name-variant pair → the ``_old`` copy is archival (deprioritized, never
  removed); DIFFERENT content despite matching name pattern → both surfaced.
* .npy is metadata-only (no array content indexed); nothing is ever deleted.
* watchdog change triggers a full table + FTS rebuild.
* ``search_outputs`` dispatches through ``_dispatch_mcp_tool`` and is registered
  read-only across the HTTP + stdio surfaces.
"""
from __future__ import annotations

import json
import os
import time

import pytest

from meridian import outputs_indexer as oi


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _write(path, text: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _seed_tree(tmp_path):
    """A representative outputs tree with csv/json/npy + _old variants."""
    numpy = pytest.importorskip("numpy")
    # canonical + byte-identical archival copy (SHA confirms archival)
    _write(tmp_path / "results.csv", "temperature,pressure,volume\n300,101,22\n")
    _write(tmp_path / "results_old.csv", "temperature,pressure,volume\n300,101,22\n")
    # same _old name pattern but DIFFERENT content → both distinct, both surfaced
    _write(tmp_path / "metrics.csv", "accuracy,loss\n0.91,0.09\n")
    _write(tmp_path / "metrics_old.csv", "accuracy,loss,f1\n0.80,0.20,0.71\n")
    # json carrying a generating_script fingerprint
    _write(
        tmp_path / "plot.json",
        json.dumps({"generating_script": "plot_results.py",
                    "xdata": [1, 2, 3], "ydata": [4, 5, 6]}),
    )
    # npy — metadata only, never array content
    numpy.save(str(tmp_path / "weights.npy"), numpy.zeros((8, 8), dtype="float32"))
    return tmp_path


# ---------------------------------------------------------------------------
# fingerprint (5848e8c7)
# ---------------------------------------------------------------------------

def test_fingerprint_csv_reports_columns(tmp_path):
    _write(tmp_path / "t.csv", "alpha,beta,gamma\n1,2,3\n")
    fp = oi.file_fingerprint(str(tmp_path / "t.csv"))
    assert fp.kind == "text_content"
    assert fp.csv_columns == ["alpha", "beta", "gamma"]
    assert fp.json_keys is None


def test_fingerprint_json_reports_keys_and_generating_script(tmp_path):
    _write(
        tmp_path / "t.json",
        json.dumps({"generating_script": "make_fig.py", "series": [1, 2]}),
    )
    fp = oi.file_fingerprint(str(tmp_path / "t.json"))
    assert set(fp.json_keys) == {"generating_script", "series"}
    assert fp.generating_script == "make_fig.py"


def test_fingerprint_infers_generating_script_from_text_marker(tmp_path):
    _write(tmp_path / "t.csv", "# generated by sweep_runner.py\nx,y\n1,2\n")
    fp = oi.file_fingerprint(str(tmp_path / "t.csv"))
    assert fp.generating_script == "sweep_runner.py"


def test_fingerprint_npy_is_metadata_only_no_content(tmp_path):
    numpy = pytest.importorskip("numpy")
    numpy.save(str(tmp_path / "a.npy"), numpy.ones((3, 3)))
    fp = oi.file_fingerprint(str(tmp_path / "a.npy"))
    assert fp.kind == "metadata_only"
    assert fp.csv_columns is None and fp.json_keys is None


def test_fingerprint_unreadable_file_never_raises(tmp_path):
    fp = oi.file_fingerprint(str(tmp_path / "missing.csv"))
    assert fp.kind == "text_content"
    assert fp.csv_columns is None


# ---------------------------------------------------------------------------
# canonical-vs-archival — TWO-STAGE, never destructive
# ---------------------------------------------------------------------------

def test_archival_candidate_filename_heuristic():
    assert oi.archival_candidate("/o/run_old.csv") is True
    assert oi.archival_candidate("/o/run_old_2.csv") is True
    assert oi.archival_candidate("/o/_scratch.json") is True
    assert oi.archival_candidate("/o/run.csv") is False
    assert oi.archival_candidate("/o/older_run.csv") is False  # 'older' != '_old'


def test_identical_content_confirms_archival(tmp_path):
    _write(tmp_path / "a.csv", "x,y\n1,2\n")
    _write(tmp_path / "a_old.csv", "x,y\n1,2\n")
    cls = oi.classify_canonical_archival(
        [str(tmp_path / "a.csv"), str(tmp_path / "a_old.csv")]
    )
    assert cls[str(tmp_path / "a.csv")].is_archival is False
    old = cls[str(tmp_path / "a_old.csv")]
    assert old.is_archival is True
    assert old.canonical_path == str(tmp_path / "a.csv")


def test_different_content_same_pattern_surfaces_both(tmp_path):
    _write(tmp_path / "a.csv", "x,y\n1,2\n")
    _write(tmp_path / "a_old.csv", "x,y,z\n9,9,9\n")  # DIFFERENT content
    cls = oi.classify_canonical_archival(
        [str(tmp_path / "a.csv"), str(tmp_path / "a_old.csv")]
    )
    # Neither collapsed — the _old copy is a genuinely distinct file.
    assert cls[str(tmp_path / "a.csv")].is_archival is False
    assert cls[str(tmp_path / "a_old.csv")].is_archival is False
    assert "DIFFERS" in cls[str(tmp_path / "a_old.csv")].reason


def test_archival_pattern_without_twin_is_not_archival(tmp_path):
    _write(tmp_path / "lonely_old.csv", "x\n1\n")
    cls = oi.classify_canonical_archival([str(tmp_path / "lonely_old.csv")])
    assert cls[str(tmp_path / "lonely_old.csv")].is_archival is False


def test_classification_never_deletes_files(tmp_path):
    _write(tmp_path / "a.csv", "x\n1\n")
    _write(tmp_path / "a_old.csv", "x\n1\n")
    oi.classify_canonical_archival(
        [str(tmp_path / "a.csv"), str(tmp_path / "a_old.csv")]
    )
    # Both files still on disk — classification is purely a label.
    assert (tmp_path / "a.csv").exists()
    assert (tmp_path / "a_old.csv").exists()


# ---------------------------------------------------------------------------
# persistent table + BM25 ranking
# ---------------------------------------------------------------------------

def test_build_output_rows_covers_every_file_with_kinds(tmp_path):
    _seed_tree(tmp_path)
    rows = {os.path.basename(r.path): r for r in oi.build_output_rows(str(tmp_path))}
    assert set(rows) == {
        "results.csv", "results_old.csv", "metrics.csv", "metrics_old.csv",
        "plot.json", "weights.npy",
    }
    assert rows["results.csv"].kind == "text_content"
    assert rows["weights.npy"].kind == "metadata_only"
    assert rows["results.csv"].sha256 == rows["results_old.csv"].sha256
    assert rows["results_old.csv"].is_archival is True
    assert rows["metrics_old.csv"].is_archival is False
    assert rows["plot.json"].generating_script == "plot_results.py"
    assert rows["results.csv"].csv_columns == ["temperature", "pressure", "volume"]


def test_bm25_multiword_query_ranks_relevant_rows_first(tmp_path):
    _seed_tree(tmp_path)
    idx = oi.OutputsFtsIndex(str(tmp_path))
    try:
        n = idx.rebuild()
        assert n == 6
        hits = idx.search("accuracy loss f1", limit=6)
        assert hits, "expected BM25 matches"
        # The metrics files (which contain accuracy/loss/f1 terms) rank above
        # the temperature/pressure results files.
        top = os.path.basename(hits[0]["path"])
        assert top in {"metrics.csv", "metrics_old.csv"}
        top_paths = {os.path.basename(h["path"]) for h in hits[:2]}
        assert {"metrics.csv", "metrics_old.csv"} <= top_paths
    finally:
        idx.close()


def test_search_deprioritizes_archival_but_keeps_it(tmp_path):
    _seed_tree(tmp_path)
    idx = oi.OutputsFtsIndex(str(tmp_path))
    try:
        idx.rebuild()
        hits = {os.path.basename(h["path"]): h
                for h in idx.search("temperature pressure volume", limit=6)}
        assert "results.csv" in hits and "results_old.csv" in hits
        # archival copy is still returned (never hard-excluded)…
        assert hits["results_old.csv"]["is_archival"] is True
        assert hits["results_old.csv"]["canonical_path"] == str(tmp_path / "results.csv")
        # …but scores strictly below its canonical twin.
        assert hits["results.csv"]["score"] > hits["results_old.csv"]["score"]
    finally:
        idx.close()


def test_search_can_hard_exclude_archival(tmp_path):
    _seed_tree(tmp_path)
    idx = oi.OutputsFtsIndex(str(tmp_path))
    try:
        idx.rebuild()
        hits = idx.search(
            "temperature pressure volume", limit=6, include_archival=False
        )
        names = {os.path.basename(h["path"]) for h in hits}
        assert "results.csv" in names
        assert "results_old.csv" not in names
    finally:
        idx.close()


def test_search_finds_npy_by_name_without_content(tmp_path):
    _seed_tree(tmp_path)
    idx = oi.OutputsFtsIndex(str(tmp_path))
    try:
        idx.rebuild()
        hits = idx.search("weights", limit=6)
        names = {os.path.basename(h["path"]) for h in hits}
        assert "weights.npy" in names
        npy_hit = next(h for h in hits if h["path"].endswith("weights.npy"))
        assert npy_hit["kind"] == "metadata_only"
    finally:
        idx.close()


def test_search_empty_query_returns_empty(tmp_path):
    _seed_tree(tmp_path)
    idx = oi.OutputsFtsIndex(str(tmp_path))
    try:
        idx.rebuild()
        assert idx.search("", limit=5) == []
        assert idx.search("   ", limit=5) == []
    finally:
        idx.close()


def test_top_level_search_outputs_wrapper(tmp_path):
    _seed_tree(tmp_path)
    result = oi.search_outputs(str(tmp_path), "accuracy loss", limit=5)
    assert result["total_indexed"] == 6
    assert result["query"] == "accuracy loss"
    assert result["hits"], "expected hits"
    assert all("score" in h for h in result["hits"])


def test_search_outputs_missing_dir_returns_empty_not_error(tmp_path):
    result = oi.search_outputs(str(tmp_path / "nope"), "x")
    assert result["hits"] == []
    assert "error" in result


# ---------------------------------------------------------------------------
# incremental rebuild — the 4-minute-hang fix (5116078b)
# ---------------------------------------------------------------------------

class _CountingHasher:
    """Wraps the real SHA-256 hasher and counts calls per path."""

    def __init__(self):
        self.calls: dict[str, int] = {}

    def __call__(self, path):
        self.calls[path] = self.calls.get(path, 0) + 1
        return oi._sha256_file(path)

    @property
    def total(self) -> int:
        return sum(self.calls.values())


def test_incremental_rebuild_skips_unchanged_files(tmp_path):
    # No _old / _-prefixed names → classification never hashes, so every hash
    # call is attributable to the row build. This isolates the incremental diff.
    _write(tmp_path / "a.csv", "alpha,beta\n1,2\n")
    _write(tmp_path / "b.csv", "gamma,delta\n3,4\n")
    _write(tmp_path / "c.json", json.dumps({"k": "v"}))
    hasher = _CountingHasher()
    idx = oi.OutputsFtsIndex(str(tmp_path), hasher=hasher)
    try:
        assert idx.rebuild() == 3
        assert hasher.total == 3  # each file hashed exactly once on the cold pass

        # Nothing changed → a second rebuild re-hashes NOTHING (the whole point).
        assert idx.rebuild() == 3
        assert hasher.total == 3

        # Change ONE file (size changes → detected regardless of mtime tick).
        _write(tmp_path / "b.csv", "gamma,delta,epsilon\n3,4,5\n")
        assert idx.rebuild() == 3
        assert hasher.total == 4  # only b.csv re-hashed
        assert hasher.calls[str(tmp_path / "b.csv")] == 2
        assert hasher.calls[str(tmp_path / "a.csv")] == 1

        # Delete a file → dropped from the index without hashing anything.
        os.remove(tmp_path / "c.json")
        assert idx.rebuild() == 2
        assert hasher.total == 4
    finally:
        idx.close()


def test_rebuild_wall_clock_budget_yields_partial_and_resumes(tmp_path):
    # Distinct ALPHABETIC token per file (taga..tagl): the DuckDB FTS tokenizer
    # drops digits, so a "markerNN" scheme would collapse every file to the same
    # "marker" token and BM25 couldn't single one out.
    for i in range(12):
        _write(tmp_path / f"f{i:02d}.csv", f"tag{chr(97 + i)},x\n{i},{i}\n")

    def _slow_hasher(path):
        time.sleep(0.05)
        return oi._sha256_file(path)

    idx = oi.OutputsFtsIndex(str(tmp_path), hasher=_slow_hasher)
    try:
        # A tight budget can't process all 12 slow files → partial result, no hang.
        n1 = idx.rebuild(max_seconds=0.12)
        assert idx.last_rebuild_partial is True
        assert 0 < n1 < 12

        # Subsequent budgeted calls resume where the last left off (already-built
        # rows are cached, only the still-stale files get worked).
        for _ in range(20):
            idx.rebuild(max_seconds=0.12)
            if not idx.last_rebuild_partial:
                break
        assert idx.last_rebuild_partial is False
        hits = idx.search("tagh", limit=5)  # tagh == f07's token (chr(97+7))
        assert any(h["path"].endswith("f07.csv") for h in hits)
    finally:
        idx.close()


def test_get_cached_index_reuses_and_evicts(tmp_path, monkeypatch):
    monkeypatch.setattr(oi, "_index_cache", oi.OrderedDict())
    monkeypatch.setattr(oi, "_MAX_CACHED_INDEXES", 2)
    d1, d2, d3 = (tmp_path / "d1", tmp_path / "d2", tmp_path / "d3")
    for d in (d1, d2, d3):
        d.mkdir()

    idx1 = oi._get_cached_index(str(d1))
    # Same directory → same cached instance (this is what makes rebuild cheap).
    assert oi._get_cached_index(str(d1)) is idx1

    idx2 = oi._get_cached_index(str(d2))
    assert idx2 is not idx1
    # Inserting a 3rd distinct dir evicts the LRU (d1) and closes its connection.
    oi._get_cached_index(str(d3))
    assert len(oi._index_cache) == 2
    assert oi._cache_key(str(d1)) not in oi._index_cache


def test_search_outputs_reuses_cached_index_across_calls(tmp_path, monkeypatch):
    monkeypatch.setattr(oi, "_index_cache", oi.OrderedDict())
    _seed_tree(tmp_path)
    r1 = oi.search_outputs(str(tmp_path), "accuracy loss", limit=5)
    assert r1["total_indexed"] == 6
    # A second call hits the SAME cached, already-populated index.
    key = oi._cache_key(str(tmp_path))
    cached = oi._index_cache[key]
    r2 = oi.search_outputs(str(tmp_path), "temperature pressure", limit=5)
    assert oi._index_cache[key] is cached
    assert r2["total_indexed"] == 6
    assert r2["hits"]


def test_invalidate_forces_rehash(tmp_path):
    _write(tmp_path / "a.csv", "alpha,beta\n1,2\n")
    hasher = _CountingHasher()
    idx = oi.OutputsFtsIndex(str(tmp_path), hasher=hasher)
    try:
        idx.rebuild()
        idx.rebuild()
        assert hasher.total == 1  # unchanged → hashed once total
        idx.invalidate(str(tmp_path / "a.csv"))
        idx.rebuild()
        assert hasher.total == 2  # forced re-hash despite unchanged mtime+size
    finally:
        idx.close()


def test_handle_event_reindexes_same_size_modify(tmp_path):
    """Watcher path is EXACT: a same-byte-length in-place edit (which the
    mtime+size heuristic alone could miss) is still reindexed, because
    handle_event force-invalidates the changed path."""
    idx = oi.OutputsIndexer(str(tmp_path))
    try:
        _write(tmp_path / "x.csv", "aaaterm,z\n1,2\n")
        idx.handle_event("created", str(tmp_path / "x.csv"))
        assert any(h["path"].endswith("x.csv")
                   for h in idx.search("aaaterm", limit=5))
        # Overwrite with identical byte length but a different searchable term.
        _write(tmp_path / "x.csv", "bbbterm,z\n1,2\n")
        idx.handle_event("modified", str(tmp_path / "x.csv"))
        assert any(h["path"].endswith("x.csv")
                   for h in idx.search("bbbterm", limit=5))
    finally:
        if idx.fts is not None:
            idx.fts.close()


# ---------------------------------------------------------------------------
# watchdog change rebuilds the FTS index
# ---------------------------------------------------------------------------

def test_handle_event_rebuilds_fts_index(tmp_path):
    """A watched-file change routed through handle_event rebuilds the persistent
    table + FTS index so a subsequent search reflects the new file."""
    idx = oi.OutputsIndexer(str(tmp_path))
    _write(tmp_path / "seed.csv", "col_a,col_b\n1,2\n")
    idx.handle_event("created", str(tmp_path / "seed.csv"))
    hits = idx.search("col_a col_b", limit=5)
    assert any(h["path"].endswith("seed.csv") for h in hits)

    # Add a second file, deliver its event → FTS index picks it up (proving the
    # rebuild-on-change, since the FTS index does NOT auto-track source changes).
    _write(tmp_path / "later.csv", "distinct_marker,other\n9,9\n")
    idx.handle_event("created", str(tmp_path / "later.csv"))
    hits2 = idx.search("distinct_marker", limit=5)
    assert any(h["path"].endswith("later.csv") for h in hits2)

    # Delete + event → rebuild drops it from search results.
    os.remove(tmp_path / "later.csv")
    idx.handle_event("deleted", str(tmp_path / "later.csv"))
    hits3 = idx.search("distinct_marker", limit=5)
    assert not any(h["path"].endswith("later.csv") for h in hits3)
    if idx.fts is not None:
        idx.fts.close()


def test_start_stop_builds_initial_fts_index(tmp_path):
    pytest.importorskip("watchdog")
    _write(tmp_path / "pre_existing.csv", "unique_term,x\n1,2\n")
    idx = oi.OutputsIndexer(str(tmp_path))
    idx.start()
    try:
        # start() ran the initial-state rebuild → pre-existing file is indexed.
        hits = idx.search("unique_term", limit=5)
        assert any(h["path"].endswith("pre_existing.csv") for h in hits)
    finally:
        idx.stop()
    assert idx.running is False


def test_end_to_end_watchdog_rebuild(tmp_path):
    """One real end-to-end pass: a native filesystem create is picked up by the
    watchdog handler, which rebuilds the FTS index so search finds the file."""
    pytest.importorskip("watchdog")
    idx = oi.OutputsIndexer(str(tmp_path))
    idx.start()
    try:
        p = os.path.join(str(tmp_path), "live.csv")
        _write(p, "livecol_marker,v\n1,2\n")
        deadline = time.time() + 10
        found = False
        while time.time() < deadline:
            hits = idx.search("livecol_marker", limit=5)
            if any(h["path"].endswith("live.csv") for h in hits):
                found = True
                break
            time.sleep(0.2)
        assert found, "watchdog-driven rebuild should surface the new file"
    finally:
        idx.stop()


# ---------------------------------------------------------------------------
# MCP registration + dispatch
# ---------------------------------------------------------------------------

def test_search_outputs_registered_read_only_in_tool_list():
    from meridian.mcp_tools import _MCP_TOOLS_LIST, _READ_ONLY_TOOLS

    by_name = {t["name"]: t for t in _MCP_TOOLS_LIST}
    assert "search_outputs" in by_name
    schema = by_name["search_outputs"]["inputSchema"]
    assert set(schema["required"]) == {"outputs_dir", "query"}
    assert "search_outputs" in _READ_ONLY_TOOLS
    assert by_name["search_outputs"]["annotations"]["readOnlyHint"] is True


def test_search_outputs_registered_in_stdio_tool_list():
    """Parse stdio_handler source: search_outputs is advertised there too."""
    import ast
    from pathlib import Path

    src = (
        Path(__file__).resolve().parents[1]
        / "meridian" / "mcp" / "stdio_handler.py"
    ).read_text(encoding="utf-8")
    tree = ast.parse(src)
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and getattr(node.func, "id", None) == "Tool":
            for k in node.keywords:
                if k.arg == "name" and isinstance(k.value, ast.Constant):
                    names.add(k.value.value)
    assert "search_outputs" in names


@pytest.mark.asyncio
async def test_search_outputs_dispatches_through_dispatch_mcp_tool(tmp_path):
    from meridian import server as srv

    _write(tmp_path / "dispatched.csv", "signal_term,other\n1,2\n")
    result = await srv._dispatch_mcp_tool(
        "search_outputs",
        {"outputs_dir": str(tmp_path), "query": "signal_term"},
        None, "/tmp",
    )
    assert isinstance(result, dict)
    assert result["query"] == "signal_term"
    assert any(h["path"].endswith("dispatched.csv") for h in result["hits"])


@pytest.mark.asyncio
async def test_dispatch_search_outputs_threads_max_seconds_through(tmp_path, monkeypatch):
    """3535b9ad -- max_seconds already existed on outputs_indexer.search_outputs
    (the "indexing slider" Adam asked for) but was never read from args or
    threaded through the search_outputs dispatch branch. Must now reach the
    underlying call."""
    from meridian import server as srv
    from meridian import outputs_indexer as _outputs_indexer

    captured = {}
    real_search_outputs = _outputs_indexer.search_outputs

    def _spy(outputs_dir, query, **kwargs):
        captured.update(kwargs)
        return real_search_outputs(outputs_dir, query, **kwargs)

    monkeypatch.setattr(_outputs_indexer, "search_outputs", _spy)
    _write(tmp_path / "budget.csv", "budget_term,other\n1,2\n")

    result = await srv._dispatch_mcp_tool(
        "search_outputs",
        {"outputs_dir": str(tmp_path), "query": "budget_term", "max_seconds": 7.5},
        None, "/tmp",
    )
    assert captured.get("max_seconds") == 7.5
    assert isinstance(result, dict)


@pytest.mark.asyncio
async def test_dispatch_search_outputs_omitted_max_seconds_uses_library_default(
    tmp_path, monkeypatch,
):
    """Omitting max_seconds must NOT pass max_seconds=None through (that would
    mean "no deadline" to the underlying function) -- it must preserve the
    library's own DEFAULT_REBUILD_BUDGET_SECONDS default, unchanged from
    before this item."""
    from meridian import server as srv
    from meridian import outputs_indexer as _outputs_indexer

    captured = {}
    real_search_outputs = _outputs_indexer.search_outputs

    def _spy(outputs_dir, query, **kwargs):
        captured.update(kwargs)
        return real_search_outputs(outputs_dir, query, **kwargs)

    monkeypatch.setattr(_outputs_indexer, "search_outputs", _spy)
    _write(tmp_path / "nodeadline.csv", "nodeadline_term,other\n1,2\n")

    await srv._dispatch_mcp_tool(
        "search_outputs",
        {"outputs_dir": str(tmp_path), "query": "nodeadline_term"},
        None, "/tmp",
    )
    assert "max_seconds" not in captured, (
        "omitting max_seconds must not override the underlying function's own "
        "default by explicitly passing max_seconds=None"
    )


@pytest.mark.asyncio
async def test_dispatch_search_outputs_requires_outputs_dir():
    from meridian import server as srv

    with pytest.raises(ValueError, match="outputs_dir is required"):
        await srv._dispatch_mcp_tool(
            "search_outputs", {"query": "x"}, None, "/tmp"
        )


@pytest.mark.asyncio
async def test_dispatch_search_outputs_requires_query(tmp_path):
    from meridian import server as srv

    with pytest.raises(ValueError, match="query is required"):
        await srv._dispatch_mcp_tool(
            "search_outputs", {"outputs_dir": str(tmp_path)}, None, "/tmp"
        )
