"""Fingerprint-based staleness invalidation for tagged outputs.

Sprint item 7518bfcd.

``outputs_local.FileFingerprint`` / ``outputs_local.file_fingerprint`` already
give a cheap, content-derived signature for one output file, including a
``generating_script`` field -- but that field is only a NAME hint pulled out
of the file's own content (e.g. a ``"generated_by": "train.py"`` key, or a
"generated by train.py" comment). It says WHICH script produced the file, but
not WHICH VERSION of that script. Two runs of a script, one buggy and one
fixed, produce the exact same ``generating_script`` string.

This module extends that concept rather than duplicating it: it reuses
``outputs_local.file_fingerprint`` for the cheap per-file signature and adds
one more dimension on top -- the content hash of the generating script
ITSELF, recorded at the moment an output is tagged. Those tags accumulate in
a small persistent ledger (JSON, under the same
``.meridian-outputs-cache/`` convention ``outputs_local`` already uses for
its FTS index, so it inherits the same gitignore-safety behaviour).

Motivating case: a generating script had a deterministic bug that silently
produced outputs identical to the branch-median. The outputs themselves
never changed run to run, so nothing about the OUTPUT file's own hash could
ever have flagged them as suspicious -- the only fossil record of "which
script version made this" is the script's content hash at generation time.
Once the bug is found and the script is fixed, :func:`find_stale_by_script`
(or the broader :func:`check_staleness`) lets every previously-tagged output
produced under the old, buggy script hash be found and flagged for
invalidation/regeneration, even though the files are otherwise
indistinguishable from a fresh, correct run.

NO hosted call is made anywhere in this module -- fully local, matching the
rest of the ``meridian_outputs`` package.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import threading
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any

from . import outputs_local

_log = logging.getLogger(__name__)

_LEDGER_FILENAME = "fingerprint_ledger.json"
_CACHE_DIRNAME = ".meridian-outputs-cache"

# Guards read-modify-write of the on-disk ledger file. A threading.Lock (not
# cross-process) mirrors the scope of outputs_local's own in-process
# _index_cache_lock -- the ledger is a lower-stakes, append-mostly sidecar,
# not the FTS index itself, so cross-process locking is not warranted here.
_write_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Ledger location (reuses the existing .meridian-outputs-cache convention)
# ---------------------------------------------------------------------------

def _cache_dir(outputs_dir: str) -> str:
    """The same ``.meridian-outputs-cache`` directory outputs_local's FTS
    index already lives under -- created + gitignored on first use so the
    ledger never needs its own separate cache-safety story."""
    cache_dir = os.path.join(outputs_dir, _CACHE_DIRNAME)
    try:
        os.makedirs(cache_dir, exist_ok=True)
        outputs_local.ensure_gitignored(cache_dir)
    except OSError:
        _log.debug(
            "fingerprint: could not create/gitignore cache dir %r",
            cache_dir, exc_info=True,
        )
    return cache_dir


def _ledger_path(outputs_dir: str) -> str:
    return os.path.join(_cache_dir(outputs_dir), _LEDGER_FILENAME)


# ---------------------------------------------------------------------------
# Script content hashing
# ---------------------------------------------------------------------------

def script_content_hash(script_path: str) -> str | None:
    """SHA-256 of a generating script's current on-disk content.

    Never raises: an unreadable/missing script yields None, mirroring
    FileFingerprint's own fail-soft contract (a script that has since been
    deleted or moved is itself useful staleness signal, handled by callers).
    """
    try:
        with open(script_path, "rb") as fh:
            return hashlib.sha256(fh.read()).hexdigest()
    except OSError:
        return None


def _resolve_script_path(
    generating_script: str, *, search_root: str | None,
) -> str | None:
    """Resolve a ``generating_script`` hint (often just a bare filename like
    ``"train.py"``) to a real path on disk.

    Tries, in order: the hint as an absolute path, the hint joined onto
    ``search_root`` (e.g. a repo root), and the hint relative to the current
    working directory. Returns None if none of those exist -- the caller
    still tags the output, just without a resolvable script hash.
    """
    if os.path.isabs(generating_script) and os.path.isfile(generating_script):
        return generating_script
    if search_root:
        candidate = os.path.join(search_root, generating_script)
        if os.path.isfile(candidate):
            return os.path.abspath(candidate)
    if os.path.isfile(generating_script):
        return os.path.abspath(generating_script)
    return None


# ---------------------------------------------------------------------------
# Tagging: FileFingerprint + generating-script hash, persisted to the ledger
# ---------------------------------------------------------------------------

@dataclass
class ScriptTaggedFingerprint:
    """A :class:`outputs_local.FileFingerprint` plus the generating script's
    content hash at tag time -- the unit stored in the ledger."""

    path: str
    kind: str
    csv_columns: list[str] | None
    json_keys: list[str] | None
    generating_script: str | None
    script_path: str | None
    script_hash: str | None
    tagged_at: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def tag_output(
    output_path: str,
    outputs_dir: str,
    *,
    script_path: str | None = None,
    search_root: str | None = None,
) -> ScriptTaggedFingerprint:
    """Fingerprint ``output_path`` and record it in the persistent ledger,
    stamped with its generating script's content hash AT THIS MOMENT.

    Reuses :func:`outputs_local.file_fingerprint` for the cheap per-file
    signature (csv_columns / json_keys / generating_script) instead of
    re-deriving it -- this module only adds the script-hash dimension on top.

    Args:
      output_path:  Absolute path to the output file to tag.
      outputs_dir:  Root outputs directory. The ledger lives under
                    ``<outputs_dir>/.meridian-outputs-cache/``, the same
                    cache convention outputs_local's FTS index already uses.
      script_path:  Explicit path to the generating script, if the caller
                    already knows it. Takes priority over the content-
                    derived ``generating_script`` hint.
      search_root:  Optional directory to resolve a bare script-name hint
                    against (e.g. a repo root) when ``script_path`` isn't
                    given explicitly.

    Returns:
      The :class:`ScriptTaggedFingerprint` that was written to the ledger.
    """
    fp = outputs_local.file_fingerprint(output_path)
    resolved = script_path
    if resolved is None and fp.generating_script:
        resolved = _resolve_script_path(fp.generating_script, search_root=search_root)
    tagged = ScriptTaggedFingerprint(
        path=output_path,
        kind=fp.kind,
        csv_columns=fp.csv_columns,
        json_keys=fp.json_keys,
        generating_script=fp.generating_script,
        script_path=resolved,
        script_hash=script_content_hash(resolved) if resolved else None,
        tagged_at=datetime.now(timezone.utc).isoformat(),
    )
    _write_ledger_entry(outputs_dir, tagged)
    return tagged


def _read_ledger(outputs_dir: str) -> dict[str, dict[str, Any]]:
    path = _ledger_path(outputs_dir)
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def _write_ledger_entry(outputs_dir: str, tagged: ScriptTaggedFingerprint) -> None:
    path = _ledger_path(outputs_dir)
    with _write_lock:
        ledger = _read_ledger(outputs_dir)
        ledger[tagged.path] = tagged.to_dict()
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(ledger, fh, indent=2, sort_keys=True)
        os.replace(tmp, path)  # atomic on both POSIX and Windows


# ---------------------------------------------------------------------------
# Staleness checks
# ---------------------------------------------------------------------------

@dataclass
class StalenessResult:
    """Whether one previously-tagged output is stale relative to its
    generating script's CURRENT on-disk content."""

    path: str
    script_path: str | None
    tagged_script_hash: str | None
    current_script_hash: str | None
    is_stale: bool
    reason: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def check_staleness(outputs_dir: str) -> list[StalenessResult]:
    """Re-hash every generating script referenced in the ledger and report
    which previously-tagged outputs are now stale.

    An output is flagged stale when its generating script's CURRENT content
    hash differs from the hash recorded at tag time -- the script has been
    edited (bug fix or otherwise) since that output was produced, so the
    output may still reflect the OLD script behaviour even though the output
    file itself never changed and looks perfectly valid/cached. It is also
    flagged stale if the generating script can no longer be read at all
    (deleted/moved -- provenance can no longer be confirmed either way).

    Returns results in stable sorted order (by output path).
    """
    ledger = _read_ledger(outputs_dir)
    results: list[StalenessResult] = []
    script_hash_cache: dict[str, str | None] = {}
    for path in sorted(ledger):
        entry = ledger[path]
        script_path = entry.get("script_path")
        tagged_hash = entry.get("script_hash")
        if not script_path:
            results.append(StalenessResult(
                path=path, script_path=None, tagged_script_hash=tagged_hash,
                current_script_hash=None, is_stale=False,
                reason="no generating script resolved at tag time",
            ))
            continue
        if script_path not in script_hash_cache:
            script_hash_cache[script_path] = script_content_hash(script_path)
        current_hash = script_hash_cache[script_path]
        if current_hash is None:
            results.append(StalenessResult(
                path=path, script_path=script_path,
                tagged_script_hash=tagged_hash, current_script_hash=None,
                is_stale=True,
                reason="generating script no longer readable/present",
            ))
        elif tagged_hash is not None and current_hash != tagged_hash:
            results.append(StalenessResult(
                path=path, script_path=script_path,
                tagged_script_hash=tagged_hash, current_script_hash=current_hash,
                is_stale=True,
                reason="generating script content changed since tagging",
            ))
        else:
            results.append(StalenessResult(
                path=path, script_path=script_path,
                tagged_script_hash=tagged_hash, current_script_hash=current_hash,
                is_stale=False,
                reason="generating script unchanged since tagging",
            ))
    return results


def find_stale_by_script(outputs_dir: str, script_path: str) -> list[str]:
    """All ledger-tagged output paths produced by ``script_path`` in a
    content state OTHER than its current on-disk content.

    This is the direct tool for the motivating scenario: "``script_path`` was
    just found buggy and fixed -- which previously-tagged outputs did the
    buggy (pre-fix) version produce?" Every ledger entry tagged against this
    script whose recorded ``script_hash`` doesn't match the script's CURRENT
    hash was generated by a script content-state that no longer exists on
    disk -- i.e. potentially the just-fixed bug.

    Returns paths in stable sorted order.
    """
    current_hash = script_content_hash(script_path)
    script_abspath = os.path.abspath(script_path)
    ledger = _read_ledger(outputs_dir)
    stale: list[str] = []
    for path in sorted(ledger):
        entry = ledger[path]
        entry_script = entry.get("script_path")
        if not entry_script or os.path.abspath(entry_script) != script_abspath:
            continue
        if entry.get("script_hash") != current_hash:
            stale.append(path)
    return stale
