"""Render the L0/L1/L2 tiered handoff markdown file for a Meridian project.

The handoff is the bridge between sessions: a new Claude session reads it
and resumes work with full context. v2.4 tiers the output:

* **L0 (Core, ~500 tokens)** — north star + active pinned decisions. The
  constitution. Always include, even in compressed paste-into-chat mode.
* **L1 (Current state, ~1500 tokens)** — sprint, version goal, last 10
  tasks, active sessions, pending sprint items. What's in flight.
* **L2 (History, ~5000 tokens)** — older task log entries, archived
  sessions, append-only decisions log. Skim if space allows.

An optional ``ai_summary`` field is generated by a tiny Haiku call when
``ANTHROPIC_API_KEY`` is set. Falls back to the first task description so
the field is always populated.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import aiosqlite
from jinja2 import Environment, FileSystemLoader, select_autoescape

from . import db as db_module

_TEMPLATE_DIR = Path(__file__).parent / "templates"
_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(disabled_extensions=("md", "j2")),
    keep_trailing_newline=True,
)


def _slugify(name: str) -> str:
    """Turn a project name into a safe filename fragment."""
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", name).strip("-")
    return slug or "project"


def _format_content(content) -> str:
    """Pretty-print goal content for the handoff body."""
    if isinstance(content, str):
        return content
    return json.dumps(content, indent=2)


def _prepare_pending_sprint_items(
    items: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Topologically order pending sprint items and annotate dependencies."""
    by_id = {item["id"]: {**item} for item in items}
    ordered: list[dict[str, Any]] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(item_id: str) -> None:
        if item_id in visited or item_id in visiting:
            return
        visiting.add(item_id)
        item = by_id[item_id]
        parent_id = item.get("depends_on")
        if parent_id and parent_id in by_id:
            visit(parent_id)
        visiting.remove(item_id)
        visited.add(item_id)
        ordered.append(item)

    for item in items:
        visit(item["id"])

    position_by_id = {item["id"]: idx + 1 for idx, item in enumerate(ordered)}
    for item in ordered:
        parent_id = item.get("depends_on")
        parent = by_id.get(parent_id) if parent_id else None
        item["dependency_title"] = parent.get("title") if parent else None
        item["dependency_status"] = parent.get("status") if parent else None
        item["dependency_position"] = (
            position_by_id.get(parent_id) if parent_id else None
        )
    return ordered


async def _generate_ai_summary(
    recent_tasks: list[dict[str, Any]],
    sprint: str | None,
    summarizer: Callable[[str], Any] | None = None,
) -> str:
    """Produce a 2-3 sentence "what was done, what's next" blurb.

    Tries a Haiku call when ``ANTHROPIC_API_KEY`` is set; otherwise falls
    back to the first task description so the field is always populated.
    Pass ``summarizer`` to inject a stub in tests.
    """
    fallback = ""
    if recent_tasks:
        first = recent_tasks[0]
        desc = (first.get("description") or "").strip()
        if desc:
            fallback = desc[:200].rstrip() + ("…" if len(desc) > 200 else "")
    if not fallback:
        fallback = "No recent activity logged."

    # Build a short prompt — capped to avoid wasting tokens on a tiny call.
    task_lines = []
    for t in recent_tasks[:8]:
        status = (t.get("status") or "?").upper()
        d = (t.get("description") or "").strip().replace("\n", " ")
        if len(d) > 160:
            d = d[:160].rstrip() + "…"
        task_lines.append(f"- [{status}] {d}")
    sprint_line = f"Sprint: {sprint.strip()}" if sprint else ""
    prompt = (
        "In 2-3 sentences (no preamble), summarize what's been done recently "
        "and the best next action. Be specific. Avoid filler.\n\n"
        f"{sprint_line}\n\n" + "\n".join(task_lines)
    )

    if summarizer is not None:
        try:
            result = summarizer(prompt)
            if hasattr(result, "__await__"):
                result = await result  # type: ignore[misc]
            if isinstance(result, dict):
                text = result.get("text") or result.get("summary") or ""
            else:
                text = str(result)
            text = text.strip()
            if text:
                return text
        except Exception:  # noqa: BLE001 — never break handoff on summary fail
            pass

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        return fallback
    try:
        import anthropic  # type: ignore[import]

        def _sync_call() -> str:
            client = anthropic.Anthropic(api_key=api_key)
            resp = client.messages.create(
                model="claude-haiku-4-5",
                max_tokens=200,
                messages=[{"role": "user", "content": prompt}],
            )
            return "".join(
                getattr(block, "text", "") for block in resp.content
            ).strip()

        loop = asyncio.get_event_loop()
        text = await asyncio.wait_for(
            loop.run_in_executor(None, _sync_call),
            timeout=30.0,
        )
        return text or fallback
    except (asyncio.TimeoutError, Exception):  # noqa: BLE001
        return fallback


async def _generate_handoff_l0(
    db: aiosqlite.Connection,
    project_id: str,
    output_dir: str,
) -> tuple[str, str]:
    """Emergency L0-only handoff — north star + pinned decisions, nothing else.

    Called as a fallback when ``generate_handoff`` times out or fails. No AI
    calls, no session summarisation, minimal DB work.
    """
    project = await db_module.get_project(db, project_id)
    name = (project or {}).get("name", project_id)
    goal = await db_module.get_goal(db, project_id)
    north_star = (goal or {}).get("north_star") or "(no north star set)"
    sprint = (goal or {}).get("sprint") or ""

    try:
        pinned = await db_module.get_pinned_decisions(db, project_id)
    except Exception:  # noqa: BLE001
        pinned = []

    lines = [
        f"# Handoff — {name}",
        f"_Generated at {datetime.now(timezone.utc).isoformat(timespec='seconds')} (L0 fallback — full handoff timed out)_",
        "",
        "## L0 — Core",
        "",
        "### North Star",
        north_star,
        "",
    ]
    if sprint:
        lines += ["### Sprint", sprint, ""]
    if pinned:
        lines += ["### Pinned Decisions"]
        for d in pinned:
            lines.append(f"- **{d.get('title', '?')}**: {d.get('body', '')}")
        lines.append("")
    lines += [
        "---",
        "_Full handoff unavailable (timeout). Run `generate_handoff` again when DB load is lower._",
    ]
    content = "\n".join(lines)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    slug = _slugify(name)
    out_path = out_dir / f"{slug}_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.resolve()), content


async def generate_handoff(
    db: aiosqlite.Connection,
    project_id: str,
    output_dir: str,
    *,
    summarizer: object | None = None,
    skip_ai_summary: bool = False,
) -> tuple[str, str]:
    """Fetch all state, render the L0/L1/L2 template, write the file, return both.

    Returns ``(path, content)`` where ``path`` is the absolute path to the
    rendered file on disk.

    Set ``skip_ai_summary=True`` for hot-path / test code that shouldn't
    burn a Haiku call. Pass ``summarizer`` to inject a stub for either
    the session-summary fan-out or the new ai_summary blurb.
    """
    project = await db_module.get_project(db, project_id)
    if project is None:
        raise ValueError(f"project not found: {project_id}")

    goal = await db_module.get_goal(db, project_id)
    if goal is None:
        goal = {
            "version": 0,
            "content": "(no goal set yet)",
            "north_star": None,
            "sprint": None,
        }
    else:
        goal = {**goal, "content": _format_content(goal["content"])}

    sessions = await db_module.get_sessions(db, project_id, active_only=False)
    # v1.2.1 — summarise eligible sessions before reading tasks so
    # the rendered handoff can reference fresh session_summary values.
    for s in sessions:
        try:
            await db_module.summarize_session(
                db, s["id"], summarizer=summarizer
            )
        except Exception:  # noqa: BLE001 — never break handoff on summary fail
            continue
    tasks = await db_module.get_tasks(db, project_id, limit=50)

    session_names = {s["id"]: s["name"] for s in sessions}
    for t in tasks:
        session_names.setdefault(t["session_id"], "(unknown-session)")

    # v2.4 — L0/L1/L2 data sources
    pinned_decisions = await db_module.get_pinned_decisions(db, project_id)
    sprint_items_all = await db_module.get_sprint_items(db, project_id)
    pending_sprint_items = [
        it for it in sprint_items_all
        if it.get("status") in ("todo", "pending", "in_progress")
    ]
    pending_sprint_items = _prepare_pending_sprint_items(pending_sprint_items)
    decisions_log = (project.get("decisions") or "").strip()

    # Split tasks into L1 (last 10) and L2 (older).
    l1_tasks = tasks[:10]
    l2_tasks = tasks[10:]
    # Active sessions for L1; archived for L2.
    active_sessions = [
        s for s in sessions if s.get("status") in ("active", "idle")
    ]
    archived_sessions = [
        s for s in sessions if s.get("status") in ("closed", "archived")
    ]

    # v2.4 — AI summary (Haiku or fallback). Skipable for tests / hot paths.
    if skip_ai_summary:
        ai_summary = ""
    else:
        ai_summary = await _generate_ai_summary(
            l1_tasks, goal.get("sprint"), summarizer=summarizer
        )

    template = _env.get_template("handoff.md.j2")
    content = template.render(
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        project=project,
        goal=goal,
        sessions=sessions,
        active_sessions=active_sessions,
        archived_sessions=archived_sessions,
        tasks=tasks,
        l1_tasks=l1_tasks,
        l2_tasks=l2_tasks,
        session_names=session_names,
        pinned_decisions=pinned_decisions,
        pending_sprint_items=pending_sprint_items,
        decisions_log=decisions_log,
        ai_summary=ai_summary,
        quick_start_goal=(
            "/goal Complete pending sprint items in dependency order. "
            "Done when: (1) generate_handoff output includes a ## Quick Start "
            "section with a /goal invocation template, (2) claim_task rejects "
            "claims where depends_on item is not done, (3) start_session "
            "auto-releases stale claims older than 2 hours, (4) pixi run test "
            "passes 524+, (5) all pending sprint items for this run are marked "
            "complete via complete_sprint_item(), (6) generate_handoff() is "
            "called at the end. Stop after 40 turns or if HITL triggered."
        ),
    )

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_slugify(project['name'])}_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.resolve()), content
