"""Render the L0/L1/L2 tiered handoff markdown file for a Meridian project.

The handoff is the bridge between sessions: a new Claude session reads it
and resumes work with full context. v2.4 tiers the output:

* **L0 (Core, ~500 tokens)** — north star + active pinned decisions. The
  constitution. Always include, even in compressed paste-into-chat mode.
* **L1 (Current state, ~1500 tokens)** — sprint, version goal, last 10
  tasks, active sessions, pending sprint items. What's in flight.
* **L2 (History, ~5000 tokens)** — older task log entries, archived
  sessions, append-only decisions log. Skim if space allows.

An optional ``ai_summary`` field is generated by a tiny Haiku call when
``ANTHROPIC_API_KEY`` is set. Falls back to the first task description so
the field is always populated.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import aiosqlite
from jinja2 import Environment, FileSystemLoader, select_autoescape

from . import db as db_module

_TEMPLATE_DIR = Path(__file__).parent / "templates"
_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(disabled_extensions=("md", "j2")),
    keep_trailing_newline=True,
)
_DEFAULT_GOAL_TEST_FLOOR = 524
_STRATEGIC_NOTE_TAGS = {"planning", "strategy", "competitive", "acquisition"}
_SESSION_HANDOFF_STATE: dict[str, str] = {}


def _slugify(name: str) -> str:
    """Turn a project name into a safe filename fragment."""
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", name).strip("-")
    return slug or "project"


def _format_content(content) -> str:
    """Pretty-print goal content for the handoff body."""
    if isinstance(content, str):
        return content
    return json.dumps(content, indent=2)


def _prepare_pending_sprint_items(
    items: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Topologically order pending sprint items and annotate dependencies."""
    by_id = {item["id"]: {**item} for item in items}
    ordered: list[dict[str, Any]] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(item_id: str) -> None:
        if item_id in visited or item_id in visiting:
            return
        visiting.add(item_id)
        item = by_id[item_id]
        parent_id = item.get("depends_on")
        if parent_id and parent_id in by_id:
            visit(parent_id)
        visiting.remove(item_id)
        visited.add(item_id)
        ordered.append(item)

    for item in items:
        visit(item["id"])

    position_by_id = {item["id"]: idx + 1 for idx, item in enumerate(ordered)}
    for item in ordered:
        parent_id = item.get("depends_on")
        parent = by_id.get(parent_id) if parent_id else None
        item["dependency_title"] = parent.get("title") if parent else None
        item["dependency_status"] = parent.get("status") if parent else None
        item["dependency_position"] = (
            position_by_id.get(parent_id) if parent_id else None
        )
    return ordered


def _build_quick_start_goal(
    pending_sprint_items: list[dict[str, Any]],
    *,
    test_floor: int = _DEFAULT_GOAL_TEST_FLOOR,
) -> str:
    """Build the handoff /goal template from the live pending sprint item ids."""
    item_ids = [item["id"] for item in pending_sprint_items if item.get("id")]
    if not item_ids:
        return (
            "/goal Verify remaining work is complete. Done when pixi run test "
            f"passes {test_floor}+, and generate_handoff() is called at the "
            "end. Stop after 40 turns or if HITL triggered."
        )
    return (
        f"/goal Complete sprint items: {', '.join(item_ids)}. "
        "Done when all listed sprint items are marked complete via "
        f"complete_sprint_item(), pixi run test passes {test_floor}+, and "
        "generate_handoff() is called at the end. Stop after 40 turns or if "
        "HITL triggered."
    )


def resolve_handoff_mode(
    requested_mode: str | None,
    session_id: str | None = None,
) -> str:
    """Resolve the public handoff mode, auto-switching repeat sessions to delta."""
    if requested_mode in {"full", "delta", "planner"}:
        return requested_mode
    if session_id and session_id in _SESSION_HANDOFF_STATE:
        return "delta"
    return "full"


def _note_tags(note: dict[str, Any]) -> set[str]:
    raw = str(note.get("tags") or "")
    return {
        tag.strip().lower()
        for tag in raw.split(",")
        if tag.strip()
    }


def _select_strategic_notes(
    notes: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Keep only notes that help a restarted planning chat."""
    selected = []
    for note in notes:
        if _note_tags(note) & _STRATEGIC_NOTE_TAGS:
            selected.append(note)
    return selected


def _completed_after(
    completed_at: str | None,
    since_ts: str | None,
) -> bool:
    if not completed_at:
        return False
    if not since_ts:
        return True
    def _parse(ts: str) -> datetime:
        normalized = ts.strip().replace("T", " ")
        if normalized.endswith("Z"):
            normalized = normalized[:-1]
        if "+" in normalized:
            normalized = normalized.split("+", 1)[0].strip()
        if "." in normalized:
            return datetime.strptime(normalized, "%Y-%m-%d %H:%M:%S.%f")
        return datetime.strptime(normalized, "%Y-%m-%d %H:%M:%S")

    return _parse(completed_at) >= _parse(since_ts)


def _render_delta_handoff(
    project: dict[str, Any],
    *,
    generated_at: str,
    completed_items: list[dict[str, Any]],
    in_progress_items: list[dict[str, Any]],
    pending_sprint_items: list[dict[str, Any]],
    quick_start_goal: str,
) -> str:
    """Return a compact handoff for back-to-back goal runs in one session."""
    # 04f03ee4 — one-liner start instruction at very top of delta output
    lines = [
        f"To start fresh: start_session(project_id=\"{project['id']}\", session_name=\"describe-what-youre-doing\")",
        "",
        f"# Session Update — {project['name']}",
        f"_Generated at {generated_at} (delta mode)_",
        "",
    ]
    # "Currently running:" — claimed in_progress items shown first so the
    # planning chat immediately knows what's active without scrolling.
    if in_progress_items:
        lines.append("Currently running:")
        for item in in_progress_items:
            claimed = item.get("claimed_by") or ""
            suffix = f" (claimed by {claimed})" if claimed else ""
            lines.append(f"- {item['id']} — {item['title']}{suffix}")
        lines.append("")
    lines.append("Completed since last handoff:")
    if completed_items:
        for item in completed_items:
            lines.append(f"- {item['id']} — {item['title']}")
    else:
        lines.append("- none")
    lines += ["", "Pending:"]
    if pending_sprint_items:
        for item in pending_sprint_items:
            lines.append(
                f"- {item['id']} [{item['status']}] {item['title']}"
            )
    else:
        lines.append("- none")
    lines += ["", "Next:", quick_start_goal]
    return "\n".join(lines) + "\n"


async def _generate_ai_summary(
    recent_tasks: list[dict[str, Any]],
    sprint: str | None,
    summarizer: Callable[[str], Any] | None = None,
) -> str:
    """Produce a 2-3 sentence "what was done, what's next" blurb.

    Tries a Haiku call when ``ANTHROPIC_API_KEY`` is set; otherwise falls
    back to the first task description so the field is always populated.
    Pass ``summarizer`` to inject a stub in tests.
    """
    fallback = ""
    if recent_tasks:
        first = recent_tasks[0]
        desc = (first.get("description") or "").strip()
        if desc:
            fallback = desc[:200].rstrip() + ("…" if len(desc) > 200 else "")
    if not fallback:
        fallback = "No recent activity logged."

    # Build a short prompt — capped to avoid wasting tokens on a tiny call.
    task_lines = []
    for t in recent_tasks[:8]:
        status = (t.get("status") or "?").upper()
        d = (t.get("description") or "").strip().replace("\n", " ")
        if len(d) > 160:
            d = d[:160].rstrip() + "…"
        task_lines.append(f"- [{status}] {d}")
    sprint_line = f"Sprint: {sprint.strip()}" if sprint else ""
    prompt = (
        "In 2-3 sentences (no preamble), summarize what's been done recently "
        "and the best next action. Be specific. Avoid filler.\n\n"
        f"{sprint_line}\n\n" + "\n".join(task_lines)
    )

    if summarizer is not None:
        try:
            result = summarizer(prompt)
            if hasattr(result, "__await__"):
                result = await result  # type: ignore[misc]
            if isinstance(result, dict):
                text = result.get("text") or result.get("summary") or ""
            else:
                text = str(result)
            text = text.strip()
            if text:
                return text
        except Exception:  # noqa: BLE001 — never break handoff on summary fail
            pass

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        return fallback
    try:
        import anthropic  # type: ignore[import]

        def _sync_call() -> str:
            client = anthropic.Anthropic(api_key=api_key)
            resp = client.messages.create(
                model="claude-haiku-4-5",
                max_tokens=200,
                messages=[{"role": "user", "content": prompt}],
            )
            return "".join(
                getattr(block, "text", "") for block in resp.content
            ).strip()

        loop = asyncio.get_event_loop()
        text = await asyncio.wait_for(
            loop.run_in_executor(None, _sync_call),
            timeout=30.0,
        )
        return text or fallback
    except (asyncio.TimeoutError, Exception):  # noqa: BLE001
        return fallback


async def _generate_handoff_l0(
    db: aiosqlite.Connection,
    project_id: str,
    output_dir: str,
) -> tuple[str, str]:
    """Emergency L0-only handoff — north star + pinned decisions, nothing else.

    Called as a fallback when ``generate_handoff`` times out or fails. No AI
    calls, no session summarisation, minimal DB work.
    """
    project = await db_module.get_project(db, project_id)
    name = (project or {}).get("name", project_id)
    goal = await db_module.get_goal(db, project_id)
    north_star = (goal or {}).get("north_star") or "(no north star set)"
    sprint = (goal or {}).get("sprint") or ""

    try:
        pinned = await db_module.get_pinned_decisions(db, project_id)
    except Exception:  # noqa: BLE001
        pinned = []

    lines = [
        f"# Handoff — {name}",
        f"_Generated at {datetime.now(timezone.utc).isoformat(timespec='seconds')} (L0 fallback — full handoff timed out)_",
        "",
        "## L0 — Core",
        "",
        "### North Star",
        north_star,
        "",
    ]
    if sprint:
        lines += ["### Sprint", sprint, ""]
    if pinned:
        lines += ["### Pinned Decisions"]
        for d in pinned:
            lines.append(f"- **{d.get('title', '?')}**: {d.get('body', '')}")
        lines.append("")
    lines += [
        "---",
        "_Full handoff unavailable (timeout). Run `generate_handoff` again when DB load is lower._",
    ]
    content = "\n".join(lines)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    slug = _slugify(name)
    out_path = out_dir / f"{slug}_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.resolve()), content


async def generate_handoff(
    db: aiosqlite.Connection,
    project_id: str,
    output_dir: str,
    *,
    summarizer: object | None = None,
    skip_ai_summary: bool = False,
    mode: str = "full",
    session_id: str | None = None,
) -> tuple[str, str]:
    """Fetch all state, render the L0/L1/L2 template, write the file, return both.

    Returns ``(path, content)`` where ``path`` is the absolute path to the
    rendered file on disk.

    Set ``skip_ai_summary=True`` for hot-path / test code that shouldn't
    burn a Haiku call. Pass ``summarizer`` to inject a stub for either
    the session-summary fan-out or the new ai_summary blurb.
    """
    project = await db_module.get_project(db, project_id)
    if project is None:
        raise ValueError(f"project not found: {project_id}")
    if mode == "planner":
        return await _generate_planner_handoff(db, project_id, output_dir)
    if mode not in {"full", "delta"}:
        raise ValueError("mode must be 'full', 'delta', or 'planner'")

    goal = await db_module.get_goal(db, project_id)
    if goal is None:
        goal = {
            "version": 0,
            "content": "(no goal set yet)",
            "north_star": None,
            "sprint": None,
        }
    else:
        goal = {**goal, "content": _format_content(goal["content"])}

    sessions = await db_module.get_sessions(db, project_id, active_only=False)
    # v1.2.1 — summarise eligible sessions before reading tasks so
    # the rendered handoff can reference fresh session_summary values.
    for s in sessions:
        try:
            await db_module.summarize_session(
                db, s["id"], summarizer=summarizer
            )
        except Exception:  # noqa: BLE001 — never break handoff on summary fail
            continue
    tasks = await db_module.get_tasks(db, project_id, limit=50)

    session_names = {s["id"]: s["name"] for s in sessions}
    for t in tasks:
        session_names.setdefault(t["session_id"], "(unknown-session)")

    # v2.4 — L0/L1/L2 data sources
    pinned_decisions = await db_module.get_pinned_decisions(db, project_id)
    project_notes = await db_module.get_project_notes(db, project_id)
    strategic_notes = _select_strategic_notes(project_notes)
    sprint_items_all = await db_module.get_sprint_items(db, project_id)
    # Separate genuinely pending from actively-claimed in_progress items so:
    # (1) quick_start_goal only names items that haven't been claimed yet, and
    # (2) the delta output surfaces "Currently running:" at the top.
    in_progress_items = [
        it for it in sprint_items_all
        if it.get("status") == "in_progress"
    ]
    pending_sprint_items = [
        it for it in sprint_items_all
        if it.get("status") in ("todo", "pending")
    ]
    pending_sprint_items = _prepare_pending_sprint_items(pending_sprint_items)
    decisions_log = (project.get("decisions") or "").strip()
    now_utc = datetime.now(timezone.utc)
    generated_at = now_utc.isoformat(timespec="seconds")
    state_ts = now_utc.strftime("%Y-%m-%d %H:%M:%S")
    quick_start_goal = _build_quick_start_goal(pending_sprint_items)

    # Split tasks into L1 (last 10) and L2 (older).
    l1_tasks = tasks[:10]
    l2_tasks = tasks[10:]
    # Active sessions for L1; archived for L2.
    active_sessions = [
        s for s in sessions if s.get("status") in ("active", "idle")
    ]
    archived_sessions = [
        s for s in sessions if s.get("status") in ("closed", "archived")
    ]

    # v2.4 — AI summary (Haiku or fallback). Skipable for tests / hot paths.
    if skip_ai_summary:
        ai_summary = ""
    else:
        ai_summary = await _generate_ai_summary(
            l1_tasks, goal.get("sprint"), summarizer=summarizer
        )

    if mode == "delta":
        since_ts = _SESSION_HANDOFF_STATE.get(session_id, None) if session_id else None
        completed_items = [
            item for item in sprint_items_all
            if item.get("status") in {"done", "skipped", "failed", "pushed"}
            and _completed_after(item.get("completed_at"), since_ts)
        ]
        content = _render_delta_handoff(
            project,
            generated_at=generated_at,
            completed_items=completed_items,
            in_progress_items=in_progress_items,
            pending_sprint_items=pending_sprint_items,
            quick_start_goal=quick_start_goal,
        )
    else:
        template = _env.get_template("handoff.md.j2")
        content = template.render(
            generated_at=generated_at,
            project=project,
            goal=goal,
            sessions=sessions,
            active_sessions=active_sessions,
            archived_sessions=archived_sessions,
            tasks=tasks,
            l1_tasks=l1_tasks,
            l2_tasks=l2_tasks,
            session_names=session_names,
            pinned_decisions=pinned_decisions,
            strategic_notes=strategic_notes,
            pending_sprint_items=pending_sprint_items,
            decisions_log=decisions_log,
            ai_summary=ai_summary,
            quick_start_goal=quick_start_goal,
        )

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_slugify(project['name'])}_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    if session_id:
        _SESSION_HANDOFF_STATE[session_id] = state_ts
    return str(out_path.resolve()), content


async def _generate_planner_handoff(
    db: object,
    project_id: str,
    output_dir: str,
) -> tuple[str, str]:
    """Planner-optimised handoff — strategic context for a claude.ai planning chat.

    Includes: north star, pinned decisions, strategic notes, open HITL queue,
    pending sprint items, recent tasks. Excludes mechanical executor details
    (file paths, test commands, repo path) — those are for Claude Code, not the
    planning chat.

    Returns ``(path, content)`` like the full handoff.
    """
    from datetime import datetime, timezone  # noqa: PLC0415

    project = await db_module.get_project(db, project_id)
    goal = await db_module.get_goal(db, project_id)
    pinned = await db_module.get_pinned_decisions(db, project_id)
    notes = await db_module.get_project_notes(db, project_id)
    strategic = _select_strategic_notes(notes)
    pending_items = await db_module.get_sprint_items(db, project_id, status="pending")
    tasks = await db_module.get_tasks(db, project_id, limit=10)
    hitl = await db_module.list_hitl_requests(db, project_id, status="pending")

    north_star = (goal or {}).get("north_star") or (goal or {}).get("goal_north_star") or ""
    sprint = (goal or {}).get("sprint") or (goal or {}).get("goal_sprint") or ""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# Meridian Planner Handoff — {project['name']}",
        f"_Generated {now}_",
        "",
        "## North Star",
        north_star or "(not set)",
        "",
        "## Current Sprint Focus",
        sprint or "(not set)",
        "",
    ]

    if pinned:
        lines += ["## Pinned Decisions (Constitution)", ""]
        for d in pinned:
            cat = d.get("category", "")
            lines.append(f"- **[{cat}]** {d.get('title', '')} — {(d.get('body') or '')[:200]}")
        lines.append("")

    if strategic:
        lines += ["## Strategic Notes", ""]
        for n in strategic[:8]:
            lines.append(f"- **{n.get('title', '')}** — {(n.get('body') or '')[:150]}")
        lines.append("")

    if hitl:
        lines += [f"## Open HITL Requests ({len(hitl)} pending)", ""]
        for h in hitl:
            urg = h.get("urgency", "normal")
            lines.append(f"- [{urg.upper()}] `{h['id'][:8]}` — {h.get('question', '')}")
        lines.append("")

    if pending_items:
        alpha = [i for i in pending_items if i.get("version") != "post-launch"]
        lines += [f"## Pending Sprint Items ({len(alpha)} alpha-launch)", ""]
        for it in alpha[:20]:
            lines.append(f"- `{it['id'][:8]}` {it.get('title', '')[:100]}")
        lines.append("")

    if tasks:
        lines += ["## Recent Tasks (last 10)", ""]
        for t in tasks[:10]:
            ts = (t.get("created_at") or "")[:10]
            status = t.get("status", "?")
            lines.append(f"- [{status.upper()}] {ts} — {(t.get('description') or '')[:100]}")
        lines.append("")

    lines += [
        "## Start a Planning Session",
        "",
        f'```',
        f'start_session(project_id="{project_id}", session_name="planning-session")',
        f'```',
        "",
    ]

    content = "\n".join(lines)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_slugify(project['name'])}_planner_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.resolve()), content
