"""Render the L0/L1/L2 tiered handoff markdown file for a Meridian project.

The handoff is the bridge between sessions: a new Claude session reads it
and resumes work with full context. v2.4 tiers the output:

* **L0 (Core, ~500 tokens)** — north star + active pinned decisions. The
  constitution. Always include, even in compressed paste-into-chat mode.
* **L1 (Current state, ~1500 tokens)** — sprint, version goal, last 10
  tasks, active sessions, pending sprint items. What's in flight.
* **L2 (History, ~5000 tokens)** — older task log entries, archived
  sessions, append-only decisions log. Skim if space allows.

An optional ``ai_summary`` field is generated by a tiny Haiku call when
``ANTHROPIC_API_KEY`` is set. Falls back to the first task description so
the field is always populated.
"""

from __future__ import annotations

import asyncio
import functools
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import aiosqlite
from jinja2 import Environment, FileSystemLoader, select_autoescape

from . import db as db_module
from .executor_config import build_executor_config_block, has_executor_config

_TEMPLATE_DIR = Path(__file__).parent / "templates"
_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(disabled_extensions=("md", "j2")),
    keep_trailing_newline=True,
)
_DEFAULT_GOAL_TEST_FLOOR = 524
_STRATEGIC_NOTE_TAGS = {"planning", "strategy", "competitive", "acquisition"}
_SESSION_HANDOFF_STATE: dict[str, str] = {}


def _slugify(name: str) -> str:
    """Turn a project name into a safe filename fragment."""
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", name).strip("-")
    return slug or "project"


def _format_content(content) -> str:
    """Pretty-print goal content for the handoff body."""
    if isinstance(content, str):
        return content
    return json.dumps(content, indent=2)


def _prepare_pending_sprint_items(
    items: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Topologically order pending sprint items and annotate dependencies."""
    by_id = {item["id"]: {**item} for item in items}
    ordered: list[dict[str, Any]] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(item_id: str) -> None:
        if item_id in visited or item_id in visiting:
            return
        visiting.add(item_id)
        item = by_id[item_id]
        parent_id = item.get("depends_on")
        if parent_id and parent_id in by_id:
            visit(parent_id)
        visiting.remove(item_id)
        visited.add(item_id)
        ordered.append(item)

    for item in items:
        visit(item["id"])

    position_by_id = {item["id"]: idx + 1 for idx, item in enumerate(ordered)}
    for item in ordered:
        parent_id = item.get("depends_on")
        parent = by_id.get(parent_id) if parent_id else None
        item["dependency_title"] = parent.get("title") if parent else None
        item["dependency_status"] = parent.get("status") if parent else None
        item["dependency_position"] = (
            position_by_id.get(parent_id) if parent_id else None
        )
    return ordered


# f628b880 — non-deferential executor framing prepended to the /goal string so an
# executor session acts immediately instead of defaulting to assistant mode and
# asking for direction. (ecf69de8 makes this conditional on execution_mode.)
_EXECUTOR_GOAL_DIRECTIVE = (
    "You are an executor. Claim and execute the following sprint items "
    "immediately in order without asking for direction or confirmation. "
    "Start with the first item now. "
)

# ecf69de8 — deferential framing for execution_mode='interactive' projects. The
# /goal lists the same items but tells the session to confirm with the human
# which to start before executing, instead of running immediately.
_INTERACTIVE_GOAL_DIRECTIVE = (
    "You are assisting interactively. Review the following sprint items and "
    "confirm with the human which to start before executing. Ask for direction "
    "before claiming or changing anything. "
)


# d2c47f43 — default turn ceiling in the /goal string when the project's
# executor_config doesn't override it via `max_turns`.
_DEFAULT_GOAL_MAX_TURNS = 200


def _max_turns_from_settings(proj_settings: dict[str, Any] | None) -> int:
    """Extract executor_config.max_turns (default 200). (d2c47f43)"""
    cfg = (proj_settings or {}).get("executor_config") or {}
    if not isinstance(cfg, dict):
        return _DEFAULT_GOAL_MAX_TURNS
    raw = cfg.get("max_turns")
    try:
        val = int(raw)
        return val if val > 0 else _DEFAULT_GOAL_MAX_TURNS
    except (TypeError, ValueError):
        return _DEFAULT_GOAL_MAX_TURNS


def _build_quick_start_goal(
    pending_sprint_items: list[dict[str, Any]],
    *,
    test_floor: int = _DEFAULT_GOAL_TEST_FLOOR,
    version: str | None = None,
    execution_mode: str = "autonomous",
    max_turns: int = _DEFAULT_GOAL_MAX_TURNS,
) -> str:
    """Build the handoff /goal template from the live pending sprint item ids.

    ``version`` (a76cb7c0) scopes the /goal to a single sprint-version bucket:
    only items whose ``version`` matches are named, so a version-scoped session's
    /goal doesn't pull in backlog/other-version items. ``None`` keeps every
    pending item (legacy behaviour).

    ``execution_mode`` (ecf69de8) selects the leading directive on the items
    path: 'autonomous' (default) prepends the non-deferential executor directive
    so the session runs immediately; 'interactive' prepends a deferential
    directive so the session asks which item to start first. Any value other
    than 'interactive' is treated as autonomous.

    ``max_turns`` (d2c47f43) sets the "Stop after N turns" ceiling. Sourced from
    the project's ``executor_config.max_turns`` (default 200) so a long-running
    sprint isn't cut off at the old hardcoded 40.
    """
    try:
        _turns = int(max_turns)
        if _turns <= 0:
            _turns = _DEFAULT_GOAL_MAX_TURNS
    except (TypeError, ValueError):
        _turns = _DEFAULT_GOAL_MAX_TURNS
    if version is not None:
        pending_sprint_items = [
            item for item in pending_sprint_items
            if item.get("version") == version
        ]
    item_ids = [item["id"] for item in pending_sprint_items if item.get("id")]
    if not item_ids:
        return (
            "/goal Verify remaining work is complete. Done when pixi run test "
            f"passes {test_floor}+, and generate_handoff() is called at the "
            f"end. Stop after {_turns} turns or if HITL triggered."
        )
    directive = (
        _INTERACTIVE_GOAL_DIRECTIVE
        if execution_mode == "interactive"
        else _EXECUTOR_GOAL_DIRECTIVE
    )
    return (
        f"/goal {directive}"
        f"Complete sprint items: {', '.join(item_ids)}. "
        "Done when all listed sprint items are marked complete via "
        f"complete_sprint_item(), pixi run test passes {test_floor}+, and "
        f"generate_handoff() is called at the end. Stop after {_turns} turns or if "
        "HITL triggered."
    )


def _extract_keywords(
    text: str, extra_stop: "frozenset[str] | set[str] | None" = None
) -> set[str]:
    """Extract significant lowercase keywords from a title/description string.

    ``extra_stop`` (23e79944) is an optional second stop set removed on top of
    the base one. The possibly-done heuristic passes :data:`_MERIDIAN_STOP_WORDS`
    so Meridian-domain high-frequency terms (session/handoff/notes/decisions/…)
    don't count as keyword overlap — they appear in nearly every task-log entry
    and otherwise produced constant false ``possibly_done`` flags. Other callers
    (code-pointer / touches-files matching) pass nothing and keep those terms.
    """
    stop = {
        "a", "an", "the", "and", "or", "in", "on", "at", "to", "for",
        "of", "is", "it", "fix", "add", "update", "remove", "change",
        "with", "from", "by", "via", "use", "set", "get", "put", "new",
        "this", "that", "into", "as", "be", "has", "was", "not", "no",
    }
    words = re.findall(r"[a-z0-9_/-]{3,}", text.lower())
    kws = {w for w in words if w not in stop}
    if extra_stop:
        kws -= set(extra_stop)
    return kws


# 23e79944 — Meridian-domain high-frequency terms. These show up in almost every
# task-log entry and commit message ("complete sprint item", "generate handoff",
# "pin decision", …), so counting them as keyword overlap made _annotate_possibly_done
# flag nearly every pending item. Filtered out (on top of the base stop set) only
# in the possibly-done heuristic — code-pointer/file matching still see them since
# they're legitimate symbol names there.
_MERIDIAN_STOP_WORDS: "frozenset[str]" = frozenset({
    "session", "sessions", "handoff", "handoffs", "note", "notes",
    "decision", "decisions", "sprint", "item", "items", "task", "tasks",
    "project", "projects", "meridian", "test", "tests", "passing", "pass",
    "dashboard", "tool", "tools", "mcp", "feat", "docs", "complete",
    "completed", "log", "logs", "board", "context", "field",
})


def reconcile_sprint_items(
    pending_items: list[dict[str, Any]],
    commits: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Cross-reference pending sprint items against commit messages.

    Each commit should be a dict with 'sha' and 'message' keys.
    confidence='high' if 3+ keywords overlap, 'medium' if 1-2 keywords overlap.
    Returns only items that have at least one keyword match.
    """
    results = []
    for item in pending_items:
        title = item.get("title") or ""
        kws = _extract_keywords(title)
        if len(kws) < 2:
            continue
        matching_commits: list[dict[str, str]] = []
        max_overlap = 0
        for commit in commits:
            msg = commit.get("message") or ""
            msg_kws = _extract_keywords(msg)
            overlap = len(kws & msg_kws)
            if overlap >= 1:
                matching_commits.append({
                    "sha": (commit.get("sha") or "")[:12],
                    "message": msg[:120],
                })
                max_overlap = max(max_overlap, overlap)
        if matching_commits:
            confidence = "high" if max_overlap >= 3 else "medium"
            results.append({
                "item_id": item["id"],
                "title": title[:200],
                "matching_commits": matching_commits[:5],
                "confidence": confidence,
            })
    return results


@functools.lru_cache(maxsize=1)
def _migration_blocks() -> tuple[tuple[str, frozenset[str]], ...]:
    """Parse db/migrations.py into ``(migration_name, keyword_set)`` blocks.

    7e212375 — each block's keyword set is the words in its ``_migrate_*`` name
    plus the quoted table/column identifiers it touches, so the drift check can
    point at the specific ``_migrate_X`` that already added a thing. Cached: the
    file is static at runtime. Returns ``()`` if the file can't be read.
    """
    try:
        src = (
            Path(__file__).resolve().parent / "db" / "migrations.py"
        ).read_text(encoding="utf-8")
    except Exception:  # noqa: BLE001
        return ()
    parts = re.split(r"\nasync def (_migrate_[a-z0-9_]+)\(", src)
    blocks: list[tuple[str, frozenset[str]]] = []

    def _add(toks: set[str], ident: str) -> None:
        ident = ident.lower()
        if len(ident) >= 3:
            toks.add(ident)
        toks.update(p for p in ident.split("_") if len(p) >= 3)

    _col_types = (
        r"TEXT|INTEGER|REAL|BLOB|BOOLEAN|BOOL|TIMESTAMPTZ|TIMESTAMP|"
        r"BIGINT|BIGSERIAL|SERIAL|JSONB|JSON|NUMERIC|DATE"
    )
    # parts = [preamble, name1, body1, name2, body2, ...]
    for i in range(1, len(parts), 2):
        name = parts[i]
        body = parts[i + 1] if i + 1 < len(parts) else ""
        toks: set[str] = set()
        for p in name.replace("_migrate_", "").split("_"):
            if len(p) >= 3:
                toks.add(p)
        # Table / index names.
        for tbl in re.findall(
            r"(?:CREATE TABLE(?: IF NOT EXISTS)?|ALTER TABLE|\bON)\s+"
            r"([a-z][a-z0-9_]+)",
            body, re.I,
        ):
            _add(toks, tbl)
        # Columns added via the helper: add_column_if_missing(db, "tbl", "col", ...).
        for tbl, col in re.findall(
            r'add_column_if_missing\(\s*\w+,\s*"([^"]+)",\s*"([^"]+)"', body
        ):
            _add(toks, tbl)
            _add(toks, col)
        # Columns / ADD COLUMN declarations followed by a SQL type.
        for col in re.findall(
            rf"(?:\n\s+|ADD COLUMN(?: IF NOT EXISTS)?\s+)([a-z][a-z0-9_]+)\s+"
            rf"(?:{_col_types})",
            body, re.I,
        ):
            _add(toks, col)
        blocks.append((name, frozenset(toks)))
    return tuple(blocks)


def detect_sprint_item_drift(
    title: str,
    recent_commits: list[Any] | None = None,
    *,
    migration_blocks: "tuple[tuple[str, frozenset[str]], ...] | None" = None,
    min_overlap: int = 3,
) -> list[dict[str, Any]]:
    """Spot a sprint-item title that may already be implemented.

    7e212375 — compares the title's keywords against (1) each migration block's
    keyword set and (2) recent commit messages. A match needs ``min_overlap``
    (default 3) shared keywords. Returns ``[{kind, ref, detail}]`` — ``kind`` is
    'migration' (ref=_migrate_X) or 'commit' (ref=sha) — empty when nothing
    crosses the threshold. ``migration_blocks`` is injectable for tests; it
    defaults to :func:`_migration_blocks`.
    """
    kws = _extract_keywords(title)
    matches: list[dict[str, Any]] = []
    if len(kws) < min_overlap:
        return matches
    blocks = migration_blocks if migration_blocks is not None else _migration_blocks()
    for name, toks in blocks:
        overlap = kws & set(toks)
        if len(overlap) >= min_overlap:
            matches.append({
                "kind": "migration",
                "ref": name,
                "detail": f"shares {sorted(overlap)} with migrations.py/{name}",
            })
            break  # one schema match is enough signal
    for c in (recent_commits or []):
        if isinstance(c, str):
            msg, sha = c, ""
        else:
            msg, sha = (c.get("message") or ""), str(c.get("sha") or "")
        overlap = kws & _extract_keywords(msg)
        if len(overlap) >= min_overlap:
            matches.append({
                "kind": "commit",
                "ref": sha[:12] or msg[:40],
                "detail": msg[:120],
            })
    return matches


def extract_transcript_narrative(
    transcript_path: str,
    *,
    max_messages: int = 40,
    max_chars: int = 4000,
) -> str:
    """Read a Claude Code transcript.jsonl and return a compact work narrative.

    571b8b60 — pulls the assistant's text turns (what it said it did), NOT
    verbatim tool inputs/outputs, so the Stop hook can build a richer delta
    handoff than task-log lines alone. Bounded: keeps the last ``max_messages``
    assistant text turns, capped to ``max_chars`` (most-recent kept). Returns
    "" on any error, a missing file, or an empty/text-less transcript — callers
    treat that as "no narrative" and fall back to the plain delta.
    """
    try:
        p = Path(transcript_path)
        if not p.is_file():
            return ""
        raw = p.read_text(encoding="utf-8", errors="replace")
    except Exception:  # noqa: BLE001
        return ""
    texts: list[str] = []
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except Exception:  # noqa: BLE001 — skip non-JSON lines
            continue
        msg = obj.get("message") if isinstance(obj, dict) else None
        if not isinstance(msg, dict) or msg.get("role") != "assistant":
            continue
        content = msg.get("content")
        if isinstance(content, str):
            t = content.strip()
            if t:
                texts.append(t)
        elif isinstance(content, list):
            for block in content:
                # Assistant text blocks only — skip tool_use / tool_result noise.
                if isinstance(block, dict) and block.get("type") == "text":
                    t = (block.get("text") or "").strip()
                    if t:
                        texts.append(t)
    if not texts:
        return ""
    narrative = "\n\n".join(texts[-max_messages:]).strip()
    if len(narrative) > max_chars:
        narrative = "…" + narrative[-max_chars:]
    return narrative


def _annotate_possibly_done(
    pending_items: list[dict[str, Any]],
    recent_tasks: list[dict[str, Any]],
    recent_commits: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Flag pending sprint items whose keywords match a recent task or commit.

    Adds ``possibly_done=True`` and ``possibly_done_matches`` (list of
    matching descriptions) to any item with ≥3 keyword matches in the last
    20 tasks or last 10 commits.  Items are not modified otherwise.

    23e79944 — the overlap threshold is 3 (raised from 2) and Meridian-domain
    high-frequency terms (:data:`_MERIDIAN_STOP_WORDS`) are excluded from the
    keyword sets, so items sharing only generic words like "session"/"handoff"/
    "notes"/"decisions" with a large task log no longer trigger false positives.
    """
    # Build a corpus of recent activity texts
    corpus: list[str] = [
        str(t.get("description") or "") for t in (recent_tasks or [])[:20]
    ]
    if recent_commits:
        corpus.extend(str(c) for c in recent_commits[:10])

    for item in pending_items:
        title = item.get("title") or ""
        kws = _extract_keywords(title, _MERIDIAN_STOP_WORDS)
        if len(kws) < 3:
            continue
        matches = []
        for text in corpus:
            text_kws = _extract_keywords(text, _MERIDIAN_STOP_WORDS)
            if len(kws & text_kws) >= 3:
                matches.append(text[:120])
        if matches:
            item["possibly_done"] = True
            item["possibly_done_matches"] = matches[:3]
    return pending_items


async def _annotate_touches_files(
    db: aiosqlite.Connection,
    project_id: str,
    pending_items: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Auto-set touches_files on pending items whose title keywords match recently
    changed files (git diff --name-only HEAD~3). Persists the match to the DB so
    start_session file_warnings can reference it. Safe to skip on error."""
    import subprocess  # noqa: PLC0415
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "HEAD~3"],
            capture_output=True, text=True, timeout=5
        )
        changed_files = [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except Exception:  # noqa: BLE001
        return pending_items
    if not changed_files:
        return pending_items

    for item in pending_items:
        if item.get("touches_files"):
            continue
        title_kws = _extract_keywords(item.get("title") or "")
        if len(title_kws) < 2:
            continue
        matched = []
        for fpath in changed_files:
            # Match on filename stem and any path segment keyword
            fname = os.path.basename(fpath)
            fname_stem = os.path.splitext(fname)[0]
            path_kws = _extract_keywords(fpath.replace("/", " ").replace(".", " "))
            if fname_stem and fname_stem in title_kws:
                matched.append(fpath)
            elif len(title_kws & path_kws) >= 2:
                matched.append(fpath)
        if matched:
            touches = json.dumps(matched[:10])
            item["touches_files"] = touches
            try:
                async with db.execute(
                    "UPDATE sprint_items SET touches_files = ? WHERE id = ? AND project_id = ?",
                    (touches, item["id"], project_id),
                ) as _:
                    pass
                await db.commit()
            except Exception:  # noqa: BLE001
                pass
    return pending_items


# ---------------------------------------------------------------------------
# 91ac0199 — code-pointer enrichment. When the project's codebase is indexed
# and the `enrich_handoffs_with_code_pointers` setting is on (default True),
# generate_handoff runs a code-graph search per pending sprint item and injects
# {file, function, qualified_name} pointers into each item's handoff block so the
# next executor starts with exact locations instead of discovering at runtime.
#
# There is no in-process code-graph: the code-intel layer is an external MCP
# (codebase-memory-mcp) reached over a tunnel. So enrichment is driven through an
# injectable ``graph_searcher`` callable (mirrors the ``summarizer`` seam). When
# none is supplied, ``_resolve_graph_searcher`` returns None and enrichment
# degrades to no pointers. Every call is wrapped so this NEVER raises out of
# generate_handoff — breaking the mandatory handoff is unacceptable.
# ---------------------------------------------------------------------------

# Default flag value when the setting has never been written.
_ENRICH_CODE_POINTERS_DEFAULT = True
# Cap on items enriched per handoff — keeps a large backlog from issuing dozens
# of graph queries on every handoff.
_MAX_ENRICHED_ITEMS = 25


def _code_pointers_enabled(settings: dict[str, Any] | None) -> bool:
    """Return whether code-pointer enrichment is on for this project.

    The flag lives in the per-project ``executor_config`` JSON blob (no schema
    migration needed). Absent / unset ⇒ default True. Any explicit falsey value
    turns it off.
    """
    if not settings:
        return _ENRICH_CODE_POINTERS_DEFAULT
    cfg = settings.get("executor_config") or {}
    if not isinstance(cfg, dict) or "enrich_handoffs_with_code_pointers" not in cfg:
        return _ENRICH_CODE_POINTERS_DEFAULT
    return bool(cfg.get("enrich_handoffs_with_code_pointers"))


def _resolve_graph_searcher(
    project_id: str,
) -> Callable[[str], Any] | None:
    """Return a code-graph search callable for ``project_id`` or None.

    The default implementation returns None because the code-graph lives in an
    out-of-process MCP that is not callable synchronously from here. The seam
    exists so deployments that *do* have an in-process searcher (and tests) can
    inject one via the ``graph_searcher`` argument to ``generate_handoff``.
    """
    return None


def _coerce_match_list(result: Any) -> list[Any]:
    """Normalise a graph-search result into a list of match dicts."""
    if result is None:
        return []
    if isinstance(result, list):
        return result
    if isinstance(result, dict):
        for key in ("results", "matches", "nodes", "hits", "items"):
            val = result.get(key)
            if isinstance(val, list):
                return val
        # A single match dict (file/name keys) is itself one result.
        return [result]
    return []


def _normalize_code_pointer(match: Any) -> dict[str, str] | None:
    """Coerce a single graph-search match into a {file, function, qualified_name}
    pointer. Returns None when the match has no usable location info."""
    if not isinstance(match, dict):
        return None
    file = (
        match.get("file")
        or match.get("file_path")
        or match.get("path")
        or ""
    )
    function = (
        match.get("function")
        or match.get("name")
        or match.get("symbol")
        or ""
    )
    qualified = (
        match.get("qualified_name")
        or match.get("qualified")
        or match.get("fqn")
        or function
    )
    file = str(file).strip()
    function = str(function).strip()
    qualified = str(qualified).strip()
    if not (file or function or qualified):
        return None
    return {
        "file": file,
        "function": function,
        "qualified_name": qualified,
    }


def _code_pointer_query(title: str, kws: set[str]) -> str:
    """Build a stable, readable graph-search query from an item title."""
    return " ".join(
        w for w in re.findall(r"[a-z0-9_/-]{3,}", title.lower()) if w in kws
    ) or title.strip()


async def _annotate_code_pointers(
    pending_items: list[dict[str, Any]],
    searcher: Callable[[str], Any] | None,
) -> list[dict[str, Any]]:
    """Attach ``code_pointers`` to pending items via a code-graph search.

    For each item, build a keyword query from its title, call ``searcher``, take
    the top match, normalise it to {file, function, qualified_name}, and store it
    as ``item["code_pointers"]`` (a one-element list). Items with no match are
    left untouched.

    ``searcher`` may be a coroutine function or a plain callable; results may be
    a list, a dict with a ``results``/``matches`` key, or a single match dict.

    Robustness contract: this must NEVER raise. All failures degrade to no
    pointer for that item — generate_handoff is mandatory and breaking it is
    unacceptable.
    """
    if searcher is None:
        return pending_items
    for item in pending_items[:_MAX_ENRICHED_ITEMS]:
        if item.get("code_pointers"):
            continue
        title = item.get("title") or ""
        kws = _extract_keywords(title)
        if not kws:
            continue
        query = _code_pointer_query(title, kws)
        try:
            result = searcher(query)
            if hasattr(result, "__await__"):
                result = await result  # type: ignore[misc]
            matches = _coerce_match_list(result)
            if not matches:
                continue
            pointer = _normalize_code_pointer(matches[0])
            if pointer:
                item["code_pointers"] = [pointer]
        except Exception:  # noqa: BLE001 — enrichment is best-effort, never fatal
            continue
    return pending_items


def resolve_handoff_mode(
    requested_mode: str | None,
    session_id: str | None = None,
) -> str:
    """Resolve the public handoff mode, auto-switching repeat sessions to delta."""
    if requested_mode in {"full", "delta", "planner", "starter", "compact"}:
        return requested_mode
    if session_id and session_id in _SESSION_HANDOFF_STATE:
        return "delta"
    return "full"


def _render_starter_handoff(
    project: dict[str, Any],
    *,
    completed_items: list[dict[str, Any]],
    pending_items: list[dict[str, Any]],
    quick_start_goal: str,
) -> str:
    """Return a ≤20-line starter block for pasting into a fresh session.

    Designed for /compact restart: gives the minimal context needed to call
    start_session() and know what to work on next.
    """
    pid = project["id"]
    name = project["name"]
    lines = [
        f"project_id: {pid}",
        f'start: start_session(project_id="{pid}", session_name="describe-what-youre-doing")',
        "",
        f"# Meridian — {name}",
    ]
    # Last 5 completed (titles only — one line)
    if completed_items:
        titles = [it["title"].split(".")[0].strip()[:60] for it in completed_items[:5]]
        extra = f" (+{len(completed_items) - 5} more)" if len(completed_items) > 5 else ""
        lines += [f"Done: {', '.join(titles)}{extra}", ""]
    else:
        lines += ["Done: (none)", ""]
    # Top 3 pending items with IDs
    lines.append("# Pending")
    for i, it in enumerate(pending_items[:3], 1):
        short_title = it["title"].strip()[:80]
        lines.append(f"{i}. [{it['id'][:8]}] {short_title}")
    if not pending_items:
        lines.append("(none)")
    lines += ["", quick_start_goal]
    return "\n".join(lines) + "\n"


def _note_tags(note: dict[str, Any]) -> set[str]:
    raw = str(note.get("tags") or "")
    return {
        tag.strip().lower()
        for tag in raw.split(",")
        if tag.strip()
    }


def _select_strategic_notes(
    notes: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Keep only notes that help a restarted planning chat.

    Includes: kind='insight' notes, notes with strategic tags, and any note
    flagged priority='high' (Sprint-4 — explicit human signal that the note
    belongs in every generate_handoff and planner brief).
    """
    selected = []
    for note in notes:
        kind = (note.get("note_kind") or note.get("kind") or "").lower()
        priority = (note.get("priority") or "normal").lower()
        if kind == "insight" or priority == "high" or (_note_tags(note) & _STRATEGIC_NOTE_TAGS):
            selected.append(note)
    # High-priority notes sort to the top.
    selected.sort(key=lambda n: {"high": 0, "normal": 1, "low": 2}.get((n.get("priority") or "normal").lower(), 1))
    return selected


def _completed_after(
    completed_at: str | None,
    since_ts: str | None,
) -> bool:
    if not completed_at:
        return False
    if not since_ts:
        return True
    def _parse(ts: str) -> datetime:
        normalized = ts.strip().replace("T", " ")
        if normalized.endswith("Z"):
            normalized = normalized[:-1]
        if "+" in normalized:
            normalized = normalized.split("+", 1)[0].strip()
        if "." in normalized:
            return datetime.strptime(normalized, "%Y-%m-%d %H:%M:%S.%f")
        return datetime.strptime(normalized, "%Y-%m-%d %H:%M:%S")

    return _parse(completed_at) >= _parse(since_ts)


def _render_delta_handoff(
    project: dict[str, Any],
    *,
    generated_at: str,
    completed_items: list[dict[str, Any]],
    in_progress_items: list[dict[str, Any]],
    pending_sprint_items: list[dict[str, Any]],
    quick_start_goal: str,
) -> str:
    """Return a compact handoff for back-to-back goal runs in one session."""
    # 04f03ee4 — one-liner start instruction at very top of delta output
    lines = [
        f"To start fresh: start_session(project_id=\"{project['id']}\", session_name=\"describe-what-youre-doing\")",
        "",
        f"# Session Update — {project['name']}",
        f"_Generated at {generated_at} (delta mode)_",
        "",
    ]
    # "Currently running:" — claimed in_progress items shown first so the
    # planning chat immediately knows what's active without scrolling.
    if in_progress_items:
        lines.append("Currently running:")
        for item in in_progress_items:
            claimed = item.get("claimed_by") or ""
            suffix = f" (claimed by {claimed})" if claimed else ""
            lines.append(f"- {item['id']} — {item['title']}{suffix}")
        lines.append("")
    lines.append("Completed since last handoff:")
    if completed_items:
        for item in completed_items:
            lines.append(f"- {item['id']} — {item['title']}")
    else:
        lines.append("- none")
    lines += ["", "Pending:"]
    if pending_sprint_items:
        for item in pending_sprint_items:
            suffix = ""
            if item.get("possibly_done"):
                suffix = " ⚠ possibly done — verify before executing"
            lines.append(
                f"- {item['id']} [{item['status']}] {item['title']}{suffix}"
            )
    else:
        lines.append("- none")
    lines += ["", "Next:", quick_start_goal]
    return "\n".join(lines) + "\n"


async def _generate_ai_summary(
    recent_tasks: list[dict[str, Any]],
    sprint: str | None,
    summarizer: Callable[[str], Any] | None = None,
) -> str:
    """Produce a 2-3 sentence "what was done, what's next" blurb.

    Tries a Haiku call when ``ANTHROPIC_API_KEY`` is set; otherwise falls
    back to the first task description so the field is always populated.
    Pass ``summarizer`` to inject a stub in tests.
    """
    fallback = ""
    if recent_tasks:
        first = recent_tasks[0]
        desc = (first.get("description") or "").strip()
        if desc:
            fallback = desc[:200].rstrip() + ("…" if len(desc) > 200 else "")
    if not fallback:
        fallback = "No recent activity logged."

    # Build a short prompt — capped to avoid wasting tokens on a tiny call.
    task_lines = []
    for t in recent_tasks[:8]:
        status = (t.get("status") or "?").upper()
        d = (t.get("description") or "").strip().replace("\n", " ")
        if len(d) > 160:
            d = d[:160].rstrip() + "…"
        task_lines.append(f"- [{status}] {d}")
    sprint_line = f"Sprint: {sprint.strip()}" if sprint else ""
    prompt = (
        "In 2-3 sentences (no preamble), summarize what's been done recently "
        "and the best next action. Be specific. Avoid filler.\n\n"
        f"{sprint_line}\n\n" + "\n".join(task_lines)
    )

    if summarizer is not None:
        try:
            result = summarizer(prompt)
            if hasattr(result, "__await__"):
                result = await result  # type: ignore[misc]
            if isinstance(result, dict):
                text = result.get("text") or result.get("summary") or ""
            else:
                text = str(result)
            text = text.strip()
            if text:
                return text
        except Exception:  # noqa: BLE001 — never break handoff on summary fail
            pass

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        return fallback
    try:
        import anthropic  # type: ignore[import]

        def _sync_call() -> str:
            client = anthropic.Anthropic(api_key=api_key)
            resp = client.messages.create(
                model="claude-haiku-4-5",
                max_tokens=200,
                messages=[{"role": "user", "content": prompt}],
            )
            return "".join(
                getattr(block, "text", "") for block in resp.content
            ).strip()

        loop = asyncio.get_event_loop()
        text = await asyncio.wait_for(
            loop.run_in_executor(None, _sync_call),
            timeout=30.0,
        )
        return text or fallback
    except (asyncio.TimeoutError, Exception):  # noqa: BLE001
        return fallback


async def _generate_handoff_l0(
    db: aiosqlite.Connection,
    project_id: str,
    output_dir: str,
) -> tuple[str, str]:
    """Emergency L0-only handoff — north star + pinned decisions, nothing else.

    Called as a fallback when ``generate_handoff`` times out or fails. No AI
    calls, no session summarisation, minimal DB work.
    """
    project = await db_module.get_project(db, project_id)
    name = (project or {}).get("name", project_id)
    goal = await db_module.get_goal(db, project_id)
    north_star = (goal or {}).get("north_star") or "(no north star set)"
    sprint = (goal or {}).get("sprint") or ""

    try:
        pinned = await db_module.get_pinned_decisions(db, project_id)
    except Exception:  # noqa: BLE001
        pinned = []

    lines = [
        f"# Handoff — {name}",
        f"_Generated at {datetime.now(timezone.utc).isoformat(timespec='seconds')} (L0 fallback — full handoff timed out)_",
        "",
        "## L0 — Core",
        "",
        "### North Star",
        north_star,
        "",
    ]
    if sprint:
        lines += ["### Sprint", sprint, ""]
    if pinned:
        lines += ["### Pinned Decisions"]
        for d in pinned:
            # 366317e9 — urgent decisions are flagged so they stand out in the
            # priority-ordered list.
            mark = " ⚡" if d.get("priority") == "urgent" else ""
            lines.append(f"- **{d.get('title', '?')}**{mark}: {d.get('body', '')}")
        lines.append("")
    lines += [
        "---",
        "_Full handoff unavailable (timeout). Run `generate_handoff` again when DB load is lower._",
    ]
    content = "\n".join(lines)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    slug = _slugify(name)
    out_path = out_dir / f"{slug}_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.resolve()), content


def _build_readiness_block(
    sprint: str | None,
    pending_count: int,
    decisions_count: int,
) -> str:
    """Build the =HANDOFF READINESS= header block prepended to every handoff."""
    lines = ["=== HANDOFF READINESS ==="]
    if sprint:
        lines.append(f"✓ Sprint: {sprint}")
    else:
        lines.append("⚠ No sprint name set")
    if pending_count == 0:
        lines.append("⚠ No pending sprint items -- add tasks before handing off to an executor")
    else:
        n = pending_count
        lines.append(f"✓ {n} pending sprint item{'s' if n != 1 else ''}")
    if decisions_count == 0:
        lines.append("⚠ No pinned decisions -- consider pinning key architectural choices")
    else:
        n = decisions_count
        lines.append(f"✓ {n} pinned decision{'s' if n != 1 else ''}")
    lines.append("=========================")
    return "\n".join(lines)


def _render_workspace_handoff_block(
    decisions: list[dict], notes: list[dict]
) -> str:
    """v3.1 — render workspace-level decisions + notes as a markdown block,
    prepended to every project's handoff. Empty string when nothing to show."""
    if not decisions and not notes:
        return ""
    lines = ["## Workspace (applies to all projects)", ""]
    if decisions:
        lines.append("### Decisions")
        for d in decisions[:10]:
            cat = (d.get("category") or "").strip()
            prefix = f"**[{cat}]** " if cat else ""
            lines.append(f"- {prefix}{d.get('title', '')} — {(d.get('body') or '')[:300]}")
        lines.append("")
    if notes:
        lines.append("### Notes")
        for n in notes[:10]:
            tags = (n.get("tags") or "").strip()
            suffix = f" _({tags})_" if tags else ""
            lines.append(f"- **{n.get('title', '')}** — {(n.get('body') or '')[:300]}{suffix}")
        lines.append("")
    return "\n".join(lines).rstrip()


def _render_custom_handoff(
    template: str,
    *,
    sprint: str | None,
    north_star: str | None,
    version_goal: str | None,
    recent_tasks: list[dict[str, Any]],
    decisions: list[dict[str, Any]],
    pending_items: list[dict[str, Any]],
    notes: list[dict[str, Any]],
) -> str:
    """Render a user-supplied handoff template (workspace_settings.handoff_template).

    Substitutes the documented ``{{placeholder}}`` tokens with plain-text
    blocks. Uses literal string replacement (not Jinja2) so a malformed or
    hostile template can never execute code or raise — unknown placeholders are
    left untouched. Empty sources render as ``(none)``.
    """
    def _tasks_block() -> str:
        if not recent_tasks:
            return "(none)"
        out = []
        for t in recent_tasks[:10]:
            status = (t.get("status") or "?").upper()
            desc = (t.get("description") or "").strip().replace("\n", " ")
            out.append(f"- [{status}] {desc[:160]}")
        return "\n".join(out)

    def _decisions_block() -> str:
        active = [d for d in decisions if d.get("status", "active") == "active"]
        if not active:
            return "(none)"
        out = []
        for d in active[:10]:
            cat = (d.get("category") or "").strip()
            prefix = f"[{cat}] " if cat else ""
            out.append(f"- {prefix}{d.get('title', '')} — {(d.get('body') or '')[:300]}")
        return "\n".join(out)

    def _pending_block() -> str:
        if not pending_items:
            return "(none)"
        out = []
        for it in pending_items[:30]:
            out.append(f"- {it['id']} [{it.get('status', '?')}] {it.get('title', '')}")
        return "\n".join(out)

    def _notes_block() -> str:
        if not notes:
            return "(none)"
        out = []
        for n in notes[:10]:
            tags = (n.get("tags") or "").strip()
            suffix = f" ({tags})" if tags else ""
            out.append(f"- {n.get('title', '')} — {(n.get('body') or '')[:300]}{suffix}")
        return "\n".join(out)

    replacements = {
        "{{sprint}}": (sprint or "").strip() or "(none)",
        "{{north_star}}": (north_star or "").strip() or "(none)",
        "{{version_goal}}": (version_goal or "").strip() or "(none)",
        "{{recent_tasks}}": _tasks_block(),
        "{{decisions}}": _decisions_block(),
        "{{pending_items}}": _pending_block(),
        "{{notes}}": _notes_block(),
    }
    rendered = template
    for token, value in replacements.items():
        rendered = rendered.replace(token, value)
    if not rendered.endswith("\n"):
        rendered += "\n"
    return rendered


async def generate_handoff(
    db: aiosqlite.Connection,
    project_id: str,
    output_dir: str,
    *,
    summarizer: object | None = None,
    skip_ai_summary: bool = False,
    mode: str = "full",
    session_id: str | None = None,
    commit_messages: list[str] | None = None,
    graph_searcher: Callable[[str], Any] | None = None,
    extra_narrative: str | None = None,
) -> tuple[str, str]:
    """Fetch all state, render the L0/L1/L2 template, write the file, return both.

    Returns ``(path, content)`` where ``path`` is the absolute path to the
    rendered file on disk.

    Set ``skip_ai_summary=True`` for hot-path / test code that shouldn't
    burn a Haiku call. Pass ``summarizer`` to inject a stub for either
    the session-summary fan-out or the new ai_summary blurb.
    """
    project = await db_module.get_project(db, project_id)
    if project is None:
        raise ValueError(f"project not found: {project_id}")
    if mode == "planner":
        return await _generate_planner_handoff(db, project_id, output_dir)
    if mode in {"starter", "compact"}:
        return await _generate_starter_handoff(db, project, output_dir)
    if mode not in {"full", "delta"}:
        raise ValueError("mode must be 'full', 'delta', 'planner', 'starter', or 'compact'")

    goal = await db_module.get_goal(db, project_id)
    if goal is None:
        goal = {
            "version": 0,
            "content": "(no goal set yet)",
            "north_star": None,
            "sprint": None,
        }
    else:
        goal = {**goal, "content": _format_content(goal["content"])}

    sessions = await db_module.get_sessions(db, project_id, active_only=False)
    # v1.2.1 — summarise eligible sessions before reading tasks so
    # the rendered handoff can reference fresh session_summary values.
    for s in sessions:
        try:
            await db_module.summarize_session(
                db, s["id"], summarizer=summarizer
            )
        except Exception:  # noqa: BLE001 — never break handoff on summary fail
            continue
    tasks = await db_module.get_tasks(db, project_id, limit=50)

    session_names = {s["id"]: s["name"] for s in sessions}
    for t in tasks:
        session_names.setdefault(t["session_id"], "(unknown-session)")

    # v2.4 — L0/L1/L2 data sources
    pinned_decisions = await db_module.get_pinned_decisions(db, project_id)
    # 5a5bba43 — handoff renders note bodies, so request the full rows.
    project_notes = await db_module.get_project_notes(db, project_id, bodies=True)
    strategic_notes = _select_strategic_notes(project_notes)
    # v3.1 — workspace decisions + notes apply across all projects.
    workspace_decisions = await db_module.get_workspace_decisions(db)
    workspace_notes = await db_module.get_workspace_notes(db)
    sprint_items_all = await db_module.get_sprint_items(db, project_id, include_human=False)
    # Separate genuinely pending from actively-claimed in_progress items so:
    # (1) quick_start_goal only names items that haven't been claimed yet, and
    # (2) the delta output surfaces "Currently running:" at the top.
    # Human-typed items are excluded from executor goal context.
    in_progress_items = [
        it for it in sprint_items_all
        if it.get("status") == "in_progress"
    ]
    pending_sprint_items = [
        it for it in sprint_items_all
        if it.get("status") in ("todo", "pending")
    ]
    pending_sprint_items = _prepare_pending_sprint_items(pending_sprint_items)
    # Flag items that may already be done based on recent task descriptions or commits
    pending_sprint_items = _annotate_possibly_done(pending_sprint_items, tasks, commit_messages)
    # Auto-set touches_files from recent git history for items without it.
    pending_sprint_items = await _annotate_touches_files(db, project_id, pending_sprint_items)
    # 91ac0199 — enrich each pending item with exact code pointers when the
    # codebase is indexed and the setting is on. Fully guarded: any failure
    # (no settings, code intel off/unindexed, searcher raising) degrades to no
    # pointers and never breaks the mandatory handoff.
    try:
        proj_settings = await db_module.get_project_settings(db, project_id)
    except Exception:  # noqa: BLE001 — settings fetch must never break handoff
        proj_settings = None
    if _code_pointers_enabled(proj_settings):
        searcher = graph_searcher or _resolve_graph_searcher(project_id)
        if searcher is not None:
            try:
                pending_sprint_items = await _annotate_code_pointers(
                    pending_sprint_items, searcher
                )
            except Exception:  # noqa: BLE001 — enrichment is best-effort
                pass
    decisions_log = (project.get("decisions") or "").strip()
    now_utc = datetime.now(timezone.utc)
    generated_at = now_utc.isoformat(timespec="seconds")
    state_ts = now_utc.strftime("%Y-%m-%d %H:%M:%S")
    # ecf69de8 — the project's executor posture selects the /goal framing.
    quick_start_goal = _build_quick_start_goal(
        pending_sprint_items,
        execution_mode=db_module.normalize_execution_mode(
            project.get("execution_mode")
        ),
        max_turns=_max_turns_from_settings(proj_settings),
    )

    # Split tasks into L1 (last 10) and L2 (older).
    l1_tasks = tasks[:10]
    l2_tasks = tasks[10:]
    # Active sessions for L1; archived for L2.
    active_sessions = [
        s for s in sessions if s.get("status") in ("active", "idle")
    ]
    archived_sessions = [
        s for s in sessions if s.get("status") in ("closed", "archived")
    ]

    # v2.4 — AI summary (Haiku or fallback). Skipable for tests / hot paths.
    if skip_ai_summary:
        ai_summary = ""
    else:
        ai_summary = await _generate_ai_summary(
            l1_tasks, goal.get("sprint"), summarizer=summarizer
        )

    if mode == "delta":
        since_ts = _SESSION_HANDOFF_STATE.get(session_id, None) if session_id else None
        completed_items = [
            item for item in sprint_items_all
            if item.get("status") in {"done", "skipped", "failed", "pushed"}
            and _completed_after(item.get("completed_at"), since_ts)
        ]
        content = _render_delta_handoff(
            project,
            generated_at=generated_at,
            completed_items=completed_items,
            in_progress_items=in_progress_items,
            pending_sprint_items=pending_sprint_items,
            quick_start_goal=quick_start_goal,
        )
    else:
        # v1.1 — per-user handoff template. When workspace_settings.handoff_template
        # is set, render it instead of the default Jinja2 template. NULL/empty =
        # default (no behavior change for existing users).
        try:
            ws_settings = await db_module.get_workspace_settings(db)
        except Exception:  # noqa: BLE001 — column may be absent on older DBs
            ws_settings = {}
        custom_tpl = (ws_settings or {}).get("handoff_template")
        if custom_tpl:
            content = _render_custom_handoff(
                custom_tpl,
                sprint=goal.get("sprint"),
                north_star=goal.get("north_star"),
                version_goal=goal.get("content"),
                recent_tasks=l1_tasks,
                decisions=pinned_decisions,
                pending_items=pending_sprint_items,
                notes=strategic_notes,
            )
        else:
            template = _env.get_template("handoff.md.j2")
            content = template.render(
                generated_at=generated_at,
                project=project,
                goal=goal,
                sessions=sessions,
                active_sessions=active_sessions,
                archived_sessions=archived_sessions,
                tasks=tasks,
                l1_tasks=l1_tasks,
                l2_tasks=l2_tasks,
                session_names=session_names,
                pinned_decisions=pinned_decisions,
                strategic_notes=strategic_notes,
                pending_sprint_items=pending_sprint_items,
                decisions_log=decisions_log,
                ai_summary=ai_summary,
                quick_start_goal=quick_start_goal,
            )

    ws_block = _render_workspace_handoff_block(
        workspace_decisions, workspace_notes
    )
    if ws_block:
        content = f"{ws_block}\n\n{content}"

    readiness_block = _build_readiness_block(
        sprint=goal.get("sprint"),
        pending_count=len(pending_sprint_items),
        decisions_count=len([d for d in pinned_decisions if d.get("status") == "active"]),
    )
    content = f"{readiness_block}\n\n{content}"

    # 10e6b265 — session queue: append the queued next-session goal (if any) and
    # clear it so the handoff surfaces the next /goal inline, exactly once.
    try:
        queued_goal = await db_module.pop_queued_session(db, project_id)
    except Exception:  # noqa: BLE001 — column may be absent on older DBs
        queued_goal = None
    if queued_goal:
        content = (
            f"{content}\n\n=== QUEUED NEXT SESSION ===\n"
            f"{queued_goal}\n=== END QUEUE ==="
        )

    # 571b8b60 — enrich the body with a transcript-derived work narrative when
    # the Stop hook supplies one (richer than task-log lines alone).
    if extra_narrative:
        content = (
            f"{content}\n\n## Session narrative (from transcript)\n\n"
            f"{extra_narrative.strip()}\n"
        )

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_slugify(project['name'])}_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    if session_id:
        _SESSION_HANDOFF_STATE[session_id] = state_ts
    # 8819d6b1 — persist this handoff to the history table so the dashboard /
    # planner can list past handoffs and detect new ones. Never break handoff
    # generation if the insert fails (e.g. pre-migration DB).
    try:
        await db_module.record_handoff(db, project_id, mode, content, session_id)
    except Exception:  # noqa: BLE001
        pass
    return str(out_path.resolve()), content


async def _generate_planner_handoff(
    db: object,
    project_id: str,
    output_dir: str,
) -> tuple[str, str]:
    """Planner-optimised handoff — a *directive planning-session prompt*.

    Unlike the executor handoffs, this is not a state dump for resuming work.
    It is an instruction set for a fresh claude.ai planning chat: it tells the
    next planning session which tools to call and in what order, surfaces the
    real items and decisions that need attention, and hands over a structured
    thinking scaffold to fill in. Mechanical executor details (file paths, test
    commands, repo path) are deliberately omitted — those belong to Claude Code.

    Sections, in order:
    * a header framing the chat as a planning session,
    * the **call-these-tools-in-this-order** protocol (real MCP tool names),
    * north star + current sprint focus (the frame to plan against),
    * pinned decisions (the constitution to plan within),
    * strategic notes (carried context),
    * sprint items to review (real pending / in_progress items),
    * open decisions (real pending HITL requests, or "none"),
    * recent activity (last few tasks for momentum),
    * a thinking scaffold with empty labelled sections to fill.

    Every data fetch is guarded so a brand-new project with no goal, items,
    decisions, or HITLs still produces a clean, crash-free prompt with "none"
    placeholders.

    Returns ``(path, content)`` like the full handoff.
    """
    from datetime import datetime, timezone  # noqa: PLC0415

    project = await db_module.get_project(db, project_id)
    goal = await db_module.get_goal(db, project_id)

    # Guard every fetch — a fresh project may have none of these, and the
    # planner prompt must still render rather than crash mid-handoff.
    async def _safe(coro, default):
        try:
            return await coro
        except Exception:  # noqa: BLE001 — never break the planner prompt on a fetch
            return default

    pinned = await _safe(db_module.get_pinned_decisions(db, project_id), [])
    # 5a5bba43 — planner brief renders note bodies, so request the full rows.
    notes = await _safe(db_module.get_project_notes(db, project_id, bodies=True), [])
    strategic = _select_strategic_notes(notes)
    pending_items = await _safe(
        db_module.get_sprint_items(db, project_id, status="pending"), []
    )
    in_progress_items = await _safe(
        db_module.get_sprint_items(db, project_id, status="in_progress"), []
    )
    tasks = await _safe(db_module.get_tasks(db, project_id, limit=10), [])
    hitl = await _safe(
        db_module.list_hitl_requests(db, project_id, status="pending"), []
    )

    north_star = (goal or {}).get("north_star") or (goal or {}).get("goal_north_star") or ""
    sprint = (goal or {}).get("sprint") or (goal or {}).get("goal_sprint") or ""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# Meridian Planning Session — {project['name']}",
        f"_Generated {now}_",
        "",
        "You are the **planner** for this project. Your job is not to write code "
        "— it is to decide *what* should be built next and in what order, then "
        "record those decisions in Meridian so the executor sessions can pick "
        "them up. Work through the protocol below, fill in the thinking "
        "scaffold, and turn your conclusions into sprint items and decisions.",
        "",
        "## Planning protocol — call these tools in this order",
        "",
        f'1. `get_planning_brief(project_id="{project_id}")` — load the compact '
        "current state (sprint, north star, pending + in-progress items, recent "
        "tasks, active sessions, pending HITLs).",
        f'2. `get_sprint_progress(project_id="{project_id}")` — see how much of '
        "the current sprint is done vs. outstanding.",
        f'3. `list_hitl_requests(project_id="{project_id}")` — review the open '
        "human decisions blocking progress; answer or supersede them.",
        f'4. `get_pinned_decisions(project_id="{project_id}")` — re-read the '
        "constitution so new items don't contradict prior choices.",
        "5. Think through the scaffold below (current state → gaps → priorities "
        "→ proposed items → risks).",
        f'6. `add_sprint_item(project_id="{project_id}", title="...", '
        'item_group="...")` — record each proposed next item.',
        f'7. `pin_decision(project_id="{project_id}", title="...", body="...", '
        'category="...")` — record any architectural / scope decisions you made.',
        "",
        "## North Star",
        north_star or "(not set)",
        "",
        "## Current Sprint Focus",
        sprint or "(not set)",
        "",
    ]

    if pinned:
        lines += ["## Pinned Decisions (plan within these)", ""]
        for d in pinned:
            cat = d.get("category", "")
            # 366317e9 — pinned is ordered urgent → normal → low; tag urgent ones.
            prio = " ⚡urgent" if d.get("priority") == "urgent" else ""
            lines.append(f"- **[{cat}]**{prio} {d.get('title', '')} — {(d.get('body') or '')[:200]}")
        lines.append("")

    if strategic:
        lines += ["## Strategic Notes", ""]
        for n in strategic[:8]:
            lines.append(f"- **{n.get('title', '')}** — {(n.get('body') or '')[:150]}")
        lines.append("")

    # Sprint items to review — in-progress first (what's live), then pending.
    # Capped so a large backlog doesn't bury the prompt.
    lines += ["## Sprint items to review", ""]
    if in_progress_items or pending_items:
        if in_progress_items:
            lines.append("_In progress:_")
            for it in in_progress_items[:10]:
                lines.append(f"- `{it['id'][:8]}` [in_progress] {(it.get('title') or '')[:100]}")
        if pending_items:
            alpha = [i for i in pending_items if i.get("version") != "post-launch"]
            shown = alpha or pending_items
            lines.append("_Pending:_")
            for it in shown[:20]:
                lines.append(f"- `{it['id'][:8]}` [pending] {(it.get('title') or '')[:100]}")
            remaining = len(shown) - 20
            if remaining > 0:
                lines.append(f"- … (+{remaining} more pending)")
    else:
        lines.append("- none — the backlog is empty; propose the first items below.")
    lines.append("")

    # Open decisions (HITL) — the human questions blocking progress.
    lines += ["## Open decisions (HITL)", ""]
    if hitl:
        for h in hitl:
            urg = (h.get("urgency") or "normal").upper()
            lines.append(f"- [{urg}] `{(h.get('id') or '')[:8]}` — {(h.get('question') or '')[:200]}")
    else:
        lines.append("- none — no human decisions are currently pending.")
    lines.append("")

    if tasks:
        lines += ["## Recent activity (last 10 tasks)", ""]
        for t in tasks[:10]:
            ts = (t.get("created_at") or "")[:10]
            status = t.get("status", "?")
            lines.append(f"- [{status.upper()}] {ts} — {(t.get('description') or '')[:100]}")
        lines.append("")

    # Thinking scaffold — empty labelled sections for the planner to fill in.
    lines += [
        "## Thinking scaffold",
        "",
        "_Fill in each section below before recording new sprint items / "
        "decisions._",
        "",
        "### Current state",
        "_Where the project stands right now — what's shipped, what's in flight._",
        "",
        "### Gaps & risks",
        "_What's missing, fragile, or blocking; what could go wrong if ignored._",
        "",
        "### Priorities",
        "_The 1-3 things that matter most for the next sprint, ranked._",
        "",
        "### Proposed next sprint items",
        "_Concrete items to create via add_sprint_item — title + group each._",
        "",
        "### Open questions",
        "_Anything needing a human decision — raise via request_hitl if blocking._",
        "",
    ]

    content = "\n".join(lines)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_slugify(project['name'])}_planner_handoff.md"
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.resolve()), content


async def _generate_starter_handoff(
    db: object,
    project: dict[str, Any],
    output_dir: str,
) -> tuple[str, str]:
    """Compact ≤20-line starter block for paste-after-/compact or cold start.

    Contains only the essentials: project_id, start_session command,
    last 5 completed sprint items (titles), top 3 pending items with IDs,
    and a ready-to-paste /goal string.  No decisions, no north star, no
    file paths — just enough to orient and execute.
    """
    project_id = project["id"]
    sprint_items_all = await db_module.get_sprint_items(db, project_id)
    completed = [
        it for it in sprint_items_all
        if it.get("status") in {"done", "skipped", "failed", "pushed"}
    ]
    # Most-recently completed first
    completed.sort(key=lambda it: (it.get("completed_at") or ""), reverse=True)
    pending = [
        it for it in sprint_items_all
        if it.get("status") in {"pending", "todo"}
    ]
    pending = _prepare_pending_sprint_items(pending)
    settings = await db_module.get_project_settings(db, project_id)
    executor_config = (settings or {}).get("executor_config") if settings else None
    # ecf69de8 — the project's executor posture selects the /goal framing.
    quick_start_goal = _build_quick_start_goal(
        pending,
        execution_mode=db_module.normalize_execution_mode(
            project.get("execution_mode")
        ),
        max_turns=_max_turns_from_settings(settings),
    )
    content = _render_starter_handoff(
        project,
        completed_items=completed,
        pending_items=pending,
        quick_start_goal=quick_start_goal,
    )
    if has_executor_config(executor_config):
        content = f"{build_executor_config_block(executor_config)}\n\n{content}"
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_slugify(project['name'])}_starter.md"
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.resolve()), content
