# Meridian tunnel auto-start installer for Windows
# Registers a Task Scheduler job that keeps `meridian --tunnel` alive across
# logins/reboots, so claude.ai (and co-located Cursor / Claude Code) always have
# a live connection to your repo. Mirrors install_watcher.ps1.
#
# Usage:
#   irm https://usemeridian.us/install_tunnel.ps1 | iex
#   # or with pre-set values:
#   $env:MERIDIAN_URL="https://usemeridian.us"; $env:MERIDIAN_TOKEN="sk_meridian_..."; $env:MERIDIAN_REPO="C:\path\to\repo"; irm ... | iex
#
# Token handling (9784f8ef): the API token is never written to disk in plaintext
# and never appears on a command line. It is stored DPAPI-encrypted (only this
# Windows account on this machine can decrypt it) in ~/.meridian/tunnel_token.dat,
# and tunnel_launcher.ps1 reads it back into the tunnel process environment at
# start. Both files are also locked down to the current user with icacls.
# MERIDIAN_TOKEN is the canonical env var; MERIDIAN_API_KEY and BEARER_TOKEN are
# accepted as legacy aliases.

param()

$ErrorActionPreference = "Stop"

$TASK_NAME    = "MeridianTunnel"
$MERIDIAN_DIR = Join-Path $env:USERPROFILE ".meridian"

# -- helpers -------------------------------------------------------------------
function Set-MeridianOwnerOnlyAcl {
    <#
      .SYNOPSIS
      Restrict a file to the current Windows user only (icacls: drop inherited
      ACEs, grant only this account). Returns $true when applied, $false when it
      could not be (icacls missing / failed) -- never throws.
    #>
    param([Parameter(Mandatory = $true)][string]$Path)
    try {
        $user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
        $grant = $user + ':F'
        & icacls.exe $Path /inheritance:r /grant:r $grant | Out-Null
        return ($LASTEXITCODE -eq 0)
    } catch {
        return $false
    }
}

function Get-MeridianEnvToken {
    <#
      .SYNOPSIS
      Return the API token from the environment (MERIDIAN_TOKEN, then the legacy
      aliases MERIDIAN_API_KEY and BEARER_TOKEN -- same order as
      meridian.tunnel_client.TOKEN_ENV_VARS), or $null. A leading "Bearer " is
      stripped.
    #>
    foreach ($name in @('MERIDIAN_TOKEN', 'MERIDIAN_API_KEY', 'BEARER_TOKEN')) {
        $v = [Environment]::GetEnvironmentVariable($name)
        if ([string]::IsNullOrWhiteSpace($v)) { continue }
        $v = $v.Trim()
        if ($v -match '^bearer\s+') { $v = ($v -replace '^bearer\s+', '').Trim() }
        if (-not [string]::IsNullOrWhiteSpace($v)) { return $v }
    }
    return $null
}

function ConvertTo-MeridianPsLiteral {
    # A PowerShell single-quoted string literal for $Value (quotes doubled), so a
    # path or URL can never break out of the generated launcher script.
    param([string]$Value)
    return "'" + ($Value -replace "'", "''") + "'"
}

function New-MeridianLauncherText {
    <#
      .SYNOPSIS
      Build the text of tunnel_launcher.ps1. It carries NO token: it decrypts the
      DPAPI token file at start and exports it to the tunnel process environment.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$MeridianUrl,
        [Parameter(Mandatory = $true)][string]$TokenFile,
        [Parameter(Mandatory = $true)][string]$MeridianRepo,
        [Parameter(Mandatory = $true)][string]$MeridianExe
    )
    $lines = @(
        '# Auto-generated by install_tunnel.ps1 - do not edit manually.',
        '# Holds no secret: the API token is read from a DPAPI-encrypted file that only',
        '# this Windows account can decrypt, and handed to the tunnel through its',
        '# environment (never the command line or the Task definition).',
        '$ErrorActionPreference = ''Stop''',
        ('$env:MERIDIAN_URL = ' + (ConvertTo-MeridianPsLiteral $MeridianUrl)),
        ('$tokenFile = ' + (ConvertTo-MeridianPsLiteral $TokenFile)),
        '$secure = Get-Content -LiteralPath $tokenFile | ConvertTo-SecureString',
        '$bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)',
        'try {',
        '    $plain = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)',
        '    # MERIDIAN_TOKEN is canonical; MERIDIAN_API_KEY keeps older meridian builds working.',
        '    $env:MERIDIAN_TOKEN = $plain',
        '    $env:MERIDIAN_API_KEY = $plain',
        '} finally {',
        '    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)',
        '}',
        ('Set-Location -LiteralPath ' + (ConvertTo-MeridianPsLiteral $MeridianRepo)),
        ('& ' + (ConvertTo-MeridianPsLiteral $MeridianExe) + ' --tunnel --repo ' + (ConvertTo-MeridianPsLiteral $MeridianRepo))
    )
    return (($lines -join "`r`n") + "`r`n")
}

function Write-MeridianOwnerOnlyFile {
    <#
      .SYNOPSIS
      Write $Content to $Path so it is never readable by other accounts: the file
      is created empty and locked to the current user BEFORE any content lands.
      Returns $true when the ACL was applied.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    New-Item -ItemType File -Force -Path $Path | Out-Null
    $hardened = Set-MeridianOwnerOnlyAcl -Path $Path
    Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8
    return $hardened
}

# -- locate the meridian executable -------------------------------------------
# No ?. here: the null-conditional operator is PowerShell 7-only, and this
# installer must also parse on the Windows PowerShell 5.1 that ships with Windows.
$MeridianCmd = Get-Command meridian -ErrorAction SilentlyContinue
$MeridianExe = if ($MeridianCmd) { $MeridianCmd.Source } else { $null }
if (-not $MeridianExe) {
    Write-Host "error: 'meridian' was not found on PATH."
    Write-Host "Install it first:  pip install meridian-server   (or:  npm i -g @meridianmcp/mcp)"
    return
}

# -- prompt for config --------------------------------------------------------
$MeridianUrl = $env:MERIDIAN_URL
if (-not $MeridianUrl) {
    $MeridianUrl = Read-Host "Meridian URL (e.g. https://usemeridian.us)"
}
$MeridianUrl = $MeridianUrl.TrimEnd("/")

# The token lives in a SecureString from here on: it is never kept in a plain
# variable, written to disk in plaintext, or placed on a command line.
$SecureToken = $null
$EnvToken = Get-MeridianEnvToken
if ($EnvToken) {
    $SecureToken = ConvertTo-SecureString -String $EnvToken -AsPlainText -Force
    $EnvToken = $null
} else {
    $SecureToken = Read-Host "Meridian API token (sk_meridian_...)" -AsSecureString
}
if ((-not $SecureToken) -or $SecureToken.Length -eq 0) {
    Write-Host "error: a Meridian API token is required."
    return
}

$MeridianRepo = $env:MERIDIAN_REPO
if (-not $MeridianRepo) {
    $MeridianRepo = Read-Host "Repo path to expose over the tunnel (blank = home directory)"
}
if (-not $MeridianRepo) { $MeridianRepo = $env:USERPROFILE }

# -- ensure target directory --------------------------------------------------
if (-not (Test-Path $MERIDIAN_DIR)) {
    New-Item -ItemType Directory -Force $MERIDIAN_DIR | Out-Null
}

# -- store the token (DPAPI-encrypted, owner-only) ----------------------------
# ConvertFrom-SecureString with no -Key uses Windows DPAPI: the blob can only be
# decrypted by this account on this machine.
$TokenFile = Join-Path $MERIDIAN_DIR "tunnel_token.dat"
$TokenBlob = $SecureToken | ConvertFrom-SecureString
$SecureToken = $null
$tokenHardened = Write-MeridianOwnerOnlyFile -Path $TokenFile -Content $TokenBlob
$TokenBlob = $null

# -- write the launcher (holds no token; out of the Task XML / `ps` output) ---
$LauncherScript = Join-Path $MERIDIAN_DIR "tunnel_launcher.ps1"
$launcherText = New-MeridianLauncherText -MeridianUrl $MeridianUrl -TokenFile $TokenFile `
    -MeridianRepo $MeridianRepo -MeridianExe $MeridianExe
# Re-running this installer overwrites any launcher written by an older version,
# which embedded the token in plaintext.
$launcherHardened = Write-MeridianOwnerOnlyFile -Path $LauncherScript -Content $launcherText
if (-not ($tokenHardened -and $launcherHardened)) {
    Write-Warning "Could not restrict the files in $MERIDIAN_DIR to your account with icacls; check their permissions."
}

# -- register Task Scheduler job ----------------------------------------------
$PwshCmd = Get-Command pwsh -ErrorAction SilentlyContinue
$PwshExe = if ($PwshCmd) { $PwshCmd.Source } else { "powershell.exe" }

$action  = New-ScheduledTaskAction -Execute $PwshExe `
               -Argument "-WindowStyle Hidden -NonInteractive -File `"$LauncherScript`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit 0 -RestartCount 3 `
                -RestartInterval (New-TimeSpan -Minutes 1) -StartWhenAvailable

# Remove old task if it exists
Unregister-ScheduledTask -TaskName $TASK_NAME -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask -TaskName $TASK_NAME -Action $action -Trigger $trigger `
    -Settings $settings -Description "Meridian tunnel (meridian --tunnel)" `
    -RunLevel Limited | Out-Null

Write-Host ""
Write-Host "Meridian tunnel installed as Task Scheduler job '$TASK_NAME'."
Write-Host "It will start automatically on next login and restart if it crashes."
Write-Host "Your token is stored DPAPI-encrypted in $TokenFile (readable only by this account)."
Write-Host ""
Write-Host "To start immediately:  Start-ScheduledTask -TaskName '$TASK_NAME'"
Write-Host "To uninstall:          Unregister-ScheduledTask -TaskName '$TASK_NAME' -Confirm:`$false"
