# Meridian file watcher installer for Windows
# Installs a persistent Task Scheduler job that fires POST /hooks/session-start
# whenever `claude --rc` creates a new session file in ~/.claude/projects/.
#
# Usage:
#   irm https://usemeridian.us/install_watcher.ps1 | iex
#   # or with pre-set values:
#   $env:MERIDIAN_URL="http://localhost:7878"; $env:MERIDIAN_TOKEN="sk_meridian_..."; irm ... | iex

param()

$ErrorActionPreference = "Stop"

$TASK_NAME  = "MeridianRcWatcher"
$WATCHER_DIR = Join-Path $env:USERPROFILE ".meridian"

# ── prompt for config ────────────────────────────────────────────────────────
$MeridianUrl = $env:MERIDIAN_URL
if (-not $MeridianUrl) {
    $MeridianUrl = Read-Host "Meridian URL (e.g. http://localhost:7878 or https://usemeridian.us)"
}
$MeridianUrl = $MeridianUrl.TrimEnd("/")

$MeridianToken = $env:MERIDIAN_TOKEN
if (-not $MeridianToken) {
    $MeridianToken = Read-Host "Meridian API token (sk_meridian_... or leave blank for local)"
}

# ── ensure target directory ──────────────────────────────────────────────────
if (-not (Test-Path $WATCHER_DIR)) {
    New-Item -ItemType Directory -Force $WATCHER_DIR | Out-Null
}

# ── write the persistent watcher script ─────────────────────────────────────
$WatcherScript = Join-Path $WATCHER_DIR "rc_watcher.ps1"

@"
# Auto-generated by install_watcher.ps1 — do not edit manually.
# Watches ~/.claude/projects/ for new session files created by `claude --rc`
# and fires POST /hooks/session-start so Meridian injects project context.

param()

`$MERIDIAN_URL   = "$MeridianUrl"
`$MERIDIAN_TOKEN = "$MeridianToken"
`$WATCH_PATH     = Join-Path `$env:USERPROFILE ".claude\projects"

function Decode-ProjectPath(`$dirName) {
    # Claude Code encodes paths as: C:\Users\foo\bar -> C--Users-foo-bar
    if (`$dirName -match '^([A-Za-z])--(.+)$') {
        `$drive = `$Matches[1]
        `$rest  = `$Matches[2] -replace '-', '\'
        return "`$drive:\`$rest"
    }
    # Unix path: /Users/foo/bar -> Users-foo-bar
    return "/" + (`$dirName -replace '-', '/')
}

function Fire-Hook(`$projectDir, `$sessionFile) {
    try {
        `$cwd      = Decode-ProjectPath `$projectDir
        `$hostname = [System.Net.Dns]::GetHostName()
        `$body     = @{ cwd = `$cwd; hostname = `$hostname; session_name = "rc-watcher" } | ConvertTo-Json
        `$headers  = @{ "Content-Type" = "application/json" }
        if (`$MERIDIAN_TOKEN) { `$headers["Authorization"] = "Bearer `$MERIDIAN_TOKEN" }
        Invoke-RestMethod -Uri "`$MERIDIAN_URL/hooks/session-start" ``
            -Method POST -Body `$body -Headers `$headers -TimeoutSec 10 | Out-Null
    } catch {
        # never crash the watcher on a hook failure
    }
}

if (-not (Test-Path `$WATCH_PATH)) {
    New-Item -ItemType Directory -Force `$WATCH_PATH | Out-Null
}

`$fsw = New-Object System.IO.FileSystemWatcher(`$WATCH_PATH)
`$fsw.IncludeSubdirectories = `$true
`$fsw.Filter                = "*.jsonl"
`$fsw.EnableRaisingEvents   = `$true

`$action = {
    `$path    = `$Event.SourceEventArgs.FullPath
    `$parts   = `$path -split [System.IO.Path]::DirectorySeparatorChar
    # path structure: .../.claude/projects/<encoded-project-dir>/<session-id>.jsonl
    if (`$parts.Count -ge 2) {
        `$projectDir = `$parts[-2]
        Fire-Hook `$projectDir `$path
    }
}

Register-ObjectEvent `$fsw Created -Action `$action | Out-Null

Write-Host "Meridian rc watcher running (watching `$WATCH_PATH). Press Ctrl+C to stop."
while (`$true) { Start-Sleep -Seconds 30 }
"@ | Set-Content -Path $WatcherScript -Encoding UTF8

# ── register Task Scheduler job ─────────────────────────────────────────────
$PwshExe = (Get-Command pwsh -ErrorAction SilentlyContinue)?.Source
if (-not $PwshExe) { $PwshExe = "powershell.exe" }

$action  = New-ScheduledTaskAction -Execute $PwshExe `
               -Argument "-WindowStyle Hidden -NonInteractive -File `"$WatcherScript`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit 0 -RestartCount 3 `
                -RestartInterval (New-TimeSpan -Minutes 1) -StartWhenAvailable

# Remove old task if it exists
Unregister-ScheduledTask -TaskName $TASK_NAME -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask -TaskName $TASK_NAME -Action $action -Trigger $trigger `
    -Settings $settings -Description "Meridian claude --rc session watcher" `
    -RunLevel Limited | Out-Null

Write-Host ""
Write-Host "Meridian rc watcher installed as Task Scheduler job '$TASK_NAME'."
Write-Host "It will start automatically on next login."
Write-Host ""
Write-Host "To start immediately:  Start-ScheduledTask -TaskName '$TASK_NAME'"
Write-Host "To uninstall:          Unregister-ScheduledTask -TaskName '$TASK_NAME' -Confirm:`$false"
