#!/usr/bin/env bash
# Meridian file watcher installer for macOS and Linux
# Installs a background service that fires POST /hooks/session-start
# whenever `claude --rc` creates a new session file in ~/.claude/projects/.
#
# Usage:
#   curl -fsSL https://usemeridian.us/install_watcher.sh | bash
#   # or with pre-set values:
#   MERIDIAN_URL=http://localhost:7878 MERIDIAN_TOKEN=sk_meridian_... bash install_watcher.sh

set -euo pipefail

WATCHER_DIR="$HOME/.meridian"
WATCHER_SCRIPT="$WATCHER_DIR/rc_watcher.sh"
WATCH_PATH="$HOME/.claude/projects"

# ── detect OS ────────────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Darwin*) PLATFORM="macos" ;;
  Linux*)  PLATFORM="linux" ;;
  *)       echo "Unsupported OS: $OS"; exit 1 ;;
esac

# ── prompt for config ────────────────────────────────────────────────────────
if [ -z "${MERIDIAN_URL:-}" ]; then
  read -rp "Meridian URL (e.g. http://localhost:7878 or https://usemeridian.us): " MERIDIAN_URL
fi
MERIDIAN_URL="${MERIDIAN_URL%/}"

if [ -z "${MERIDIAN_TOKEN:-}" ]; then
  read -rp "Meridian API token (sk_meridian_... or leave blank for local): " MERIDIAN_TOKEN || MERIDIAN_TOKEN=""
fi

# ── ensure target directory ──────────────────────────────────────────────────
mkdir -p "$WATCHER_DIR"

# ── write the persistent watcher script ─────────────────────────────────────
cat > "$WATCHER_SCRIPT" << 'SCRIPT_BODY'
#!/usr/bin/env bash
# Auto-generated by install_watcher.sh — do not edit manually.
set -euo pipefail

MERIDIAN_URL="__MERIDIAN_URL__"
MERIDIAN_TOKEN="__MERIDIAN_TOKEN__"
WATCH_PATH="$HOME/.claude/projects"

decode_project_path() {
  local dir_name="$1"
  # Claude Code path encoding: C:\Users\foo\bar -> C--Users-foo-bar
  # or /Users/foo/bar -> Users-foo-bar (Unix, leading / stripped)
  if [[ "$dir_name" =~ ^([A-Za-z])--(.+)$ ]]; then
    local drive="${BASH_REMATCH[1]}"
    local rest="${BASH_REMATCH[2]//-/\/}"
    echo "${drive}:/${rest}"
  else
    # Unix: prepend /
    echo "/${dir_name//-/\/}"
  fi
}

fire_hook() {
  local project_dir="$1"
  local cwd
  cwd="$(decode_project_path "$project_dir")"
  local hostname
  hostname="$(hostname -s 2>/dev/null || hostname)"
  local auth_header=""
  if [ -n "$MERIDIAN_TOKEN" ]; then
    auth_header="-H \"Authorization: Bearer $MERIDIAN_TOKEN\""
  fi
  local body
  body="{\"cwd\":\"$cwd\",\"hostname\":\"$hostname\",\"session_name\":\"rc-watcher\"}"
  eval curl -sf -X POST "$MERIDIAN_URL/hooks/session-start" \
    -H "Content-Type: application/json" \
    $auth_header \
    -d "$body" > /dev/null 2>&1 || true
}

mkdir -p "$WATCH_PATH"

OS="$(uname -s)"
if [[ "$OS" == "Darwin" ]]; then
  # macOS: use fswatch if available, else fall back to polling
  if command -v fswatch &>/dev/null; then
    fswatch -0 -r -e ".*" -i ".*\.jsonl$" "$WATCH_PATH" | while IFS= read -r -d "" path; do
      project_dir="$(basename "$(dirname "$path")")"
      fire_hook "$project_dir" &
    done
  else
    # Polling fallback (2s interval)
    declare -A SEEN
    while true; do
      while IFS= read -r -d "" path; do
        if [[ -z "${SEEN[$path]:-}" ]]; then
          SEEN["$path"]=1
          project_dir="$(basename "$(dirname "$path")")"
          fire_hook "$project_dir" &
        fi
      done < <(find "$WATCH_PATH" -name "*.jsonl" -newer "$WATCHER_SCRIPT" -print0 2>/dev/null)
      sleep 2
    done
  fi
elif [[ "$OS" == "Linux" ]]; then
  # Linux: use inotifywait if available, else polling
  if command -v inotifywait &>/dev/null; then
    inotifywait -q -m -r -e create --format "%w%f" "$WATCH_PATH" | while IFS= read -r path; do
      if [[ "$path" == *.jsonl ]]; then
        project_dir="$(basename "$(dirname "$path")")"
        fire_hook "$project_dir" &
      fi
    done
  else
    declare -A SEEN
    while true; do
      while IFS= read -r -d "" path; do
        if [[ -z "${SEEN[$path]:-}" ]]; then
          SEEN["$path"]=1
          project_dir="$(basename "$(dirname "$path")")"
          fire_hook "$project_dir" &
        fi
      done < <(find "$WATCH_PATH" -name "*.jsonl" -newer "$WATCHER_SCRIPT" -print0 2>/dev/null)
      sleep 2
    done
  fi
fi
SCRIPT_BODY

# Substitute config values
sed -i.bak \
  -e "s|__MERIDIAN_URL__|${MERIDIAN_URL}|g" \
  -e "s|__MERIDIAN_TOKEN__|${MERIDIAN_TOKEN}|g" \
  "$WATCHER_SCRIPT"
rm -f "${WATCHER_SCRIPT}.bak"
chmod +x "$WATCHER_SCRIPT"

# ── register background service ──────────────────────────────────────────────
if [ "$PLATFORM" = "macos" ]; then
  PLIST_LABEL="us.usemeridian.rc-watcher"
  PLIST_DIR="$HOME/Library/LaunchAgents"
  PLIST_FILE="$PLIST_DIR/${PLIST_LABEL}.plist"

  mkdir -p "$PLIST_DIR"

  cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${WATCHER_SCRIPT}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${WATCHER_DIR}/rc_watcher.log</string>
  <key>StandardErrorPath</key>
  <string>${WATCHER_DIR}/rc_watcher.log</string>
</dict>
</plist>
EOF

  # Unload if already loaded
  launchctl unload "$PLIST_FILE" 2>/dev/null || true
  launchctl load "$PLIST_FILE"

  echo ""
  echo "Meridian rc watcher installed as LaunchAgent '${PLIST_LABEL}'."
  echo "Starts automatically at login."
  echo ""
  echo "To stop:      launchctl unload '${PLIST_FILE}'"
  echo "To uninstall: rm '${PLIST_FILE}' && launchctl unload '${PLIST_FILE}'"

elif [ "$PLATFORM" = "linux" ]; then
  SERVICE_DIR="$HOME/.config/systemd/user"
  SERVICE_FILE="$SERVICE_DIR/meridian-rc-watcher.service"

  mkdir -p "$SERVICE_DIR"

  cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Meridian claude --rc session watcher
After=network.target

[Service]
ExecStart=${WATCHER_SCRIPT}
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable meridian-rc-watcher.service
  systemctl --user start meridian-rc-watcher.service

  echo ""
  echo "Meridian rc watcher installed as systemd user service 'meridian-rc-watcher'."
  echo ""
  echo "To check status: systemctl --user status meridian-rc-watcher"
  echo "To uninstall:    systemctl --user disable --now meridian-rc-watcher && rm '${SERVICE_FILE}'"
fi
