# Meridian tunnel auto-start installer for Windows
# Registers a Task Scheduler job that keeps `meridian --tunnel` alive across
# logins/reboots, so claude.ai (and co-located Cursor / Claude Code) always have
# a live connection to your repo. Mirrors install_watcher.ps1.
#
# Usage:
#   irm https://usemeridian.us/install_tunnel.ps1 | iex
#   # or with pre-set values:
#   $env:MERIDIAN_URL="https://usemeridian.us"; $env:MERIDIAN_API_KEY="sk_meridian_..."; $env:MERIDIAN_REPO="C:\path\to\repo"; irm ... | iex

param()

$ErrorActionPreference = "Stop"

$TASK_NAME    = "MeridianTunnel"
$MERIDIAN_DIR = Join-Path $env:USERPROFILE ".meridian"

# -- locate the meridian executable -------------------------------------------
$MeridianExe = (Get-Command meridian -ErrorAction SilentlyContinue)?.Source
if (-not $MeridianExe) {
    Write-Host "error: 'meridian' was not found on PATH."
    Write-Host "Install it first:  pip install meridian-server   (or:  npm i -g meridian-mcp)"
    return
}

# -- prompt for config --------------------------------------------------------
$MeridianUrl = $env:MERIDIAN_URL
if (-not $MeridianUrl) {
    $MeridianUrl = Read-Host "Meridian URL (e.g. https://usemeridian.us)"
}
$MeridianUrl = $MeridianUrl.TrimEnd("/")

$MeridianToken = $env:MERIDIAN_API_KEY
if (-not $MeridianToken) {
    $MeridianToken = Read-Host "Meridian API token (sk_meridian_...)"
}

$MeridianRepo = $env:MERIDIAN_REPO
if (-not $MeridianRepo) {
    $MeridianRepo = Read-Host "Repo path to expose over the tunnel (blank = home directory)"
}
if (-not $MeridianRepo) { $MeridianRepo = $env:USERPROFILE }

# -- ensure target directory --------------------------------------------------
if (-not (Test-Path $MERIDIAN_DIR)) {
    New-Item -ItemType Directory -Force $MERIDIAN_DIR | Out-Null
}

# -- write the launcher (keeps the token out of the Task XML / `ps` output) ---
$LauncherScript = Join-Path $MERIDIAN_DIR "tunnel_launcher.ps1"

@"
# Auto-generated by install_tunnel.ps1 - do not edit manually.
# Sets the tunnel's auth env vars (out of the Task definition + process args)
# and keeps `meridian --tunnel` running.
`$env:MERIDIAN_URL     = "$MeridianUrl"
`$env:MERIDIAN_API_KEY = "$MeridianToken"
Set-Location "$MeridianRepo"
& "$MeridianExe" --tunnel --repo "$MeridianRepo"
"@ | Set-Content -Path $LauncherScript -Encoding UTF8

# -- register Task Scheduler job ----------------------------------------------
$PwshExe = (Get-Command pwsh -ErrorAction SilentlyContinue)?.Source
if (-not $PwshExe) { $PwshExe = "powershell.exe" }

$action  = New-ScheduledTaskAction -Execute $PwshExe `
               -Argument "-WindowStyle Hidden -NonInteractive -File `"$LauncherScript`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit 0 -RestartCount 3 `
                -RestartInterval (New-TimeSpan -Minutes 1) -StartWhenAvailable

# Remove old task if it exists
Unregister-ScheduledTask -TaskName $TASK_NAME -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask -TaskName $TASK_NAME -Action $action -Trigger $trigger `
    -Settings $settings -Description "Meridian tunnel (meridian --tunnel)" `
    -RunLevel Limited | Out-Null

Write-Host ""
Write-Host "Meridian tunnel installed as Task Scheduler job '$TASK_NAME'."
Write-Host "It will start automatically on next login and restart if it crashes."
Write-Host ""
Write-Host "To start immediately:  Start-ScheduledTask -TaskName '$TASK_NAME'"
Write-Host "To uninstall:          Unregister-ScheduledTask -TaskName '$TASK_NAME' -Confirm:`$false"
