#!/usr/bin/env bash
# Meridian tunnel auto-start installer for macOS and Linux
# Registers a background service (LaunchAgent / systemd user unit) that keeps
# `meridian --tunnel` alive across logins/reboots. Mirrors install_watcher.sh.
#
# Usage:
#   curl -fsSL https://usemeridian.us/install_tunnel.sh | bash
#   # or with pre-set values:
#   MERIDIAN_URL=https://usemeridian.us MERIDIAN_API_KEY=sk_meridian_... MERIDIAN_REPO=/path/to/repo bash install_tunnel.sh

set -euo pipefail

MERIDIAN_DIR="$HOME/.meridian"
LAUNCHER="$MERIDIAN_DIR/tunnel_launcher.sh"

# -- detect OS ----------------------------------------------------------------
OS="$(uname -s)"
case "$OS" in
  Darwin*) PLATFORM="macos" ;;
  Linux*)  PLATFORM="linux" ;;
  *)       echo "Unsupported OS: $OS"; exit 1 ;;
esac

# -- locate meridian ----------------------------------------------------------
MERIDIAN_BIN="$(command -v meridian || true)"
if [ -z "$MERIDIAN_BIN" ]; then
  echo "error: 'meridian' was not found on PATH."
  echo "Install it first:  pip install meridian-server   (or:  npm i -g meridian-mcp)"
  exit 1
fi

# -- prompt for config --------------------------------------------------------
if [ -z "${MERIDIAN_URL:-}" ]; then
  read -rp "Meridian URL (e.g. https://usemeridian.us): " MERIDIAN_URL
fi
MERIDIAN_URL="${MERIDIAN_URL%/}"

if [ -z "${MERIDIAN_API_KEY:-}" ]; then
  read -rp "Meridian API token (sk_meridian_...): " MERIDIAN_API_KEY || MERIDIAN_API_KEY=""
fi

if [ -z "${MERIDIAN_REPO:-}" ]; then
  read -rp "Repo path to expose over the tunnel (blank = home directory): " MERIDIAN_REPO || MERIDIAN_REPO=""
fi
[ -z "$MERIDIAN_REPO" ] && MERIDIAN_REPO="$HOME"

# -- ensure target directory --------------------------------------------------
mkdir -p "$MERIDIAN_DIR"

# -- write the launcher (keeps the token out of the unit/plist + `ps` output) -
cat > "$LAUNCHER" << EOF
#!/usr/bin/env bash
# Auto-generated by install_tunnel.sh - do not edit manually.
set -euo pipefail
export MERIDIAN_URL="${MERIDIAN_URL}"
export MERIDIAN_API_KEY="${MERIDIAN_API_KEY}"
cd "${MERIDIAN_REPO}"
exec "${MERIDIAN_BIN}" --tunnel --repo "${MERIDIAN_REPO}"
EOF
chmod +x "$LAUNCHER"

# -- register background service ----------------------------------------------
if [ "$PLATFORM" = "macos" ]; then
  PLIST_LABEL="us.usemeridian.tunnel"
  PLIST_DIR="$HOME/Library/LaunchAgents"
  PLIST_FILE="$PLIST_DIR/${PLIST_LABEL}.plist"

  mkdir -p "$PLIST_DIR"

  cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${LAUNCHER}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${MERIDIAN_DIR}/tunnel.log</string>
  <key>StandardErrorPath</key>
  <string>${MERIDIAN_DIR}/tunnel.log</string>
</dict>
</plist>
EOF

  # Reload if already loaded
  launchctl unload "$PLIST_FILE" 2>/dev/null || true
  launchctl load "$PLIST_FILE"

  echo ""
  echo "Meridian tunnel installed as LaunchAgent '${PLIST_LABEL}'."
  echo "Starts automatically at login and restarts if it crashes."
  echo ""
  echo "To stop:      launchctl unload '${PLIST_FILE}'"
  echo "To uninstall: launchctl unload '${PLIST_FILE}' && rm '${PLIST_FILE}'"

elif [ "$PLATFORM" = "linux" ]; then
  SERVICE_DIR="$HOME/.config/systemd/user"
  SERVICE_FILE="$SERVICE_DIR/meridian-tunnel.service"

  mkdir -p "$SERVICE_DIR"

  cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Meridian tunnel (meridian --tunnel)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=${LAUNCHER}
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable meridian-tunnel.service
  systemctl --user start meridian-tunnel.service

  echo ""
  echo "Meridian tunnel installed as systemd user service 'meridian-tunnel'."
  echo "Tip: run 'loginctl enable-linger $USER' so it keeps running without an active login."
  echo ""
  echo "To check status: systemctl --user status meridian-tunnel"
  echo "To uninstall:    systemctl --user disable --now meridian-tunnel && rm '${SERVICE_FILE}'"
fi
